### ISSUE TITLE
PyTango workshop @ SOLARIS - list of tasks

### ISSUE THREAD

**Issue by LJBD** [tango-controls/pytango#110]
This week we have a PyTango workshop at SOLARIS with @vxgmichel and @AntoineDupre and, as one of the goals, SOLARIS controls team is going to commit to PyTango. We've set up the following list of tasks for the workshop:
- [x] One PR for documentation
- [x] One PR for tests
- [x] One PR for PEP8-ifying an existing module.

The short presentation with topics mentioned at the workshop can be found [here](http://antoinedupre.github.io/pytango-workshop/#1) (you have to disable https in order to view it). We've a repo for examples that we've worked on [here](https://github.com/LJBD/tango-asyncio-tests).

**Comment by vxgmichel** [comment]
Thanks to everyone for their contributions!
