### ISSUE TITLE
Dynamic commands (tango9)

### ISSUE THREAD

**Issue by tiagocoutinho** [tango-controls/pytango#12]
Implement dynamic commands (server side) for PyTango 9.

**Comment by Athanaseus** [comment]
@tiagocoutinho is the feature already been added for PyTango_9.2.0?

**Comment by tiagocoutinho** [comment]
@Athanaseus no it has not. It is now marked for milestone 9.2.1. Would you like to help :-) ?

**Comment by Athanaseus** [comment]
Hi @tiagocoutinho yes I'm interested in this feature, and would not mind trying to implement it. Maybe you can direct me along the right course for getting started?

**Comment by tiagocoutinho** [comment]
Before you start you should synchronize with @grm84 because he is in charge of this task.

The idea is to implement in PyTango Device the same functionality that was added to C++:

* [`DeviceImpl.add_command()`](http://www.esrf.eu/computing/cs/tango/tango_doc/kernel_doc/cpp_doc/classTango_1_1DeviceImpl.html#a64f3aafd381cd25bb562cdb4074932d9)
* [`DeviceImpl.remove_command()`](http://www.esrf.eu/computing/cs/tango/tango_doc/kernel_doc/cpp_doc/classTango_1_1DeviceImpl.html#ae57fcb9d357314f6e4f159a62de3fb8d)

You could make a proposal in this issue for a pythonic API and the PyTango team could comment on it.
Hint: similar thing was done for dynamic attributes (see [How to create attributes dynamically](http://pytango.readthedocs.io/en/latest/howto.html?highlight=add_attribute#create-attributes-dynamically) and [PyTango add_attribute() API](http://pytango.readthedocs.io/en/latest/server_api/device.html?highlight=add_attribute#tango.LatestDeviceImpl.add_attribute)

The proposal should focus on the new server API style and if possible make it possible for the old API but in my opinion it is not essencial. It should also include in the doc a how-to since this sort of things are not always evident in Tango on how to do.
