### ISSUE TITLE
Pipe events (tango9)

### ISSUE THREAD

**Issue by tiagocoutinho** [tango-controls/pytango#13]
Implement pipe events (client and server) for PyTango 9

**Comment by reszelaz** [comment]
I'm interested in this feature. What is the time estimation for having it? Unfortunately I don't have time to help in the development but I could be the _beta_ tester.

**Comment by tiagocoutinho** [comment]
Hi @reszelaz,
@grm84 just finished the implementation and I have accepted the MR #104 into develop.
Feel free to test and report any problems.

**Comment by reszelaz** [comment]
Thanks for the update. I will let you know whenever we have some results of the tests.
