### ISSUE TITLE
server.run swallows any raised exception

### ISSUE THREAD

**Issue by vxgmichel** [tango-controls/pytango#131]
The current implementation of `server.run` catches any exception raised while trying to run the server. It does log it though, with or without the traceback, depending on the `msg_stream` and `verbose` arguments. In my opinion, a more pythonic approach is to let the user code handle the exception (if necessary). 

I think this is somehow related to issue #132 (server side helper for parsing DS arguments). A clean approach could be to provide two helpers:

- a python run helper:
  * take python arguments
  * run the server 
  * raise exceptions
- a CLI run helper:
  * take command line arguments
  * parse them
  * run the python helper
  * catch, format and print exceptions

A simpler approach could also be to add a `raises` argument to the existing run functions.

**Comment by LJBD** [comment]
Do we have an issue for the argparse task?

**Comment by vxgmichel** [comment]
@LJBD Not yet, I'll take care of it.

**Comment by vxgmichel** [comment]
@LJBD Done!

**Comment by LJBD** [comment]
Okay, so now I have a possibly dumb question to the proposed implementation:
Why do we need two helpers? I have an idea about what a CLI helper would do, but not so much about the other one - is it supposed to help to run servers programmatically with Python scripts?

**Comment by vxgmichel** [comment]
>  is it supposed to help to run servers programmatically with Python scripts?

Exactly. Typically, servers usually provide a `run` and `main` function:

```python
def run(host='', port=8888):
    [...]

def main(args=None):
    if args is None:
        args = sys.argv
    host, port = some_parsing(args)
    try:
        run(host, port)
    except Exception as e:
        # proper exception handling
        print(e)

if __name__ == '__main__':
    main()
```

Then you can either do:

```console
$ python -c "from myserver import run; run(port=9999)" # Or
$ python -m myserver --port 9999
```

But maybe that doesn't apply so well to pytango, considering backward compatibility and the different ways we have to  run a server...

**Comment by AntoineDupre** [comment]
Working on it !

My proposal:
 * Add ```catch_exception=True``` argument to ```run``` and ```run_server``` (from server.py)
```python
def run(classes, args=None, msg_stream=sys.stdout,                               
    verbose=False, util=None, event_loop=None,                               
    post_init_callback=None, green_mode=None,                                
    catch_exception=True): 
```

 * Update the ```DeviceTestContext``` with the same ```catch_exception``` argument that forward the exception to the main Thread/Process to let user test code handle it. 
Wrap server run method like:
```python
def wrap_run_method(self, *args, **kwargs):
    try:
        self.server_runner(*args, **kwargs)
    except Exception as e:
        self.queue.put(e)
``` 

And raise the exception in the context manager ```__exit__``` method:
```python
def __exit__(self, exc_type, exception, trace): 
    self.stop()
    try:
        e = self.queue.get()
        if isinstance(e, Exception):
            raise e
    except queue.Empty:
        pass
```

This might not work if an exception is raised in ```init_device``` (in that case the test might crashed with an ```terminate called after throwing an instance of 'omni_thread_fatal'``` error)

**Comment by LJBD** [comment]
IMHO a CLI helper is a much needed feature since I'd *like* to see the errors that initialisation of my devices produce. A Python helper is more of a nice-to-have thing to me.

EDIT, after seeing @AntoineDupre's suggestion: this would be a nice robust solution of the issue. I like that!

**Comment by vxgmichel** [comment]
@LJBD Yea, the CLI+python helpers approach is painful to implement for very little reward. @AntoineDupre's proposal is much simpler, so let's stick to that!
