### ISSUE TITLE
Releasing pytango 9.2.2

### ISSUE THREAD

**Issue by vxgmichel** [tango-controls/pytango#139]
Now that @grm84 PRs have been merged, I think it's time to release pytango-9.2.2, and change the milestone for the pending issues to 9.2.3. Is it OK with everyone?

For the record, the release procedure includes:

- [x] Editing the changelog
- [x] Bumping the version
- [x] Merging develop into stable
- [x] Make sure Travis is OK
- [x] Make sure the documentation is updated
- [x] Create a release tag on GitHub
- [x] Upload the new version to PyPI
- [x] Bumping the version with "-dev" in the develop branch
- [x] Fill the release description on GitHub
- [x] Advertise the release on the mailing list

Is anyone interested in taking care of it?

**Comment by vxgmichel** [comment]
Pinging...

I'd rather not do it myself since I want more people to know about this procedure, but I'll be happy to help!

**Comment by vxgmichel** [comment]
Pinging... @LJBD @AntoineDupre @tiagocoutinho @cmft @reszelaz

I'd rather not do it myself since I want more people to know about this procedure, but I'll be happy to help!

**Comment by LJBD** [comment]
I think that I'll have some time on Thursday so I can do something then.

**Comment by vxgmichel** [comment]
@LJBD Great! :smile: Let me know if you need help

**Comment by LJBD** [comment]
Sorry, guys, it turned out that my local tasks consumed me to a greater extent that I've forseen. I may have some time this week to start the process, but I'm certain that I won't have time to finish it.

**Comment by vxgmichel** [comment]
@LJBD It's fine, there's no hurry :wink: And spreading the release process over several weeks is no problem either. Again, I'll be happy to help anyway.

**Comment by LJBD** [comment]
The situation unwound in the most astounding of ways: I'm quitting my job at SOLARIS at the end of August. This means that I won't have time to prepare a PyTango release during the next 2 weeks for sure and after that it's rather unlikely.
Sorry for letting you all down.

**Comment by vxgmichel** [comment]
@jairomoldes @guifrecuni @grm84 Thanks for your help!
