### ISSUE TITLE
ImportError: cannot import name seqStr_2_obj

### ISSUE THREAD

**Issue by jkotan** [tango-controls/pytango#144]
Hi,

It looks like 9.2.2 is not backward compatible with 9.2.0, i.e.

     from PyTango import seqStr_2_obj

does not work and e.g. it causes crash of sardana Pool.

Bests,
Jan

**Comment by vxgmichel** [comment]
Oops :sweat_smile: 

Here's the list of all the objects from the `utils` module that are not exposed anymore after 01f92b9d6:

> is_scalar_type, is_array_type, is_numerical_type, is_int_type, is_float_type, is_bool_type, is_str_type, obj_2_str, str_2_obj, seqStr_2_obj

@jkotan Do you know if `seqStr_2_obj` is the only one that sardana requires?

**Comment by jkotan** [comment]
To my knowledge  for `sardana` is only `seqStr_2_obj` but it looks like `taurus` uses  also  

    is_numerical_type, is_int_type, is_float_type, is_bool_type, str_2_obj

**Comment by vxgmichel** [comment]
Fixed! Thanks for the report!
