### ISSUE TITLE
Green mode for Database object

### ISSUE THREAD

**Issue by AntoineDupre** [tango-controls/pytango#145]
Hi,

With tango client green modes, only AttributePoxy and DeviceProxy are wrapped by the green decorator to run in an executor.

The tango.Database object is not compatible with green modes, however it might be interesting to be able to write such kind of coroutines:
```python
async def main():
    db = await Database()
    await for device_name in db.get_device_name("*", "TangoTest"):
        device = await DeviceProxy(device_name)
        attr = await device.read_attribute("ampli")
```

Does it make sense to also wrapped the tango.Database with green modes ?

**Comment by tiagocoutinho** [comment]
It does!
When the greenification process started in the pre-historic era (aka before git era) I prioritized `DeviceProxy` and `AttributeProxy`. The `Database` was low priority. That is the only reason it is not done.
