### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by hasrifa2003** [tango-controls/pytango#146]
installation newest PyTango error :
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

is there any solution?

**Comment by LJBD** [comment]
Well, the error information that you've provided doesn't say much.
Please include the whole log of your installation and write us about what platform are you doing this on and what version of Tango you've got.

**Comment by hasrifa2003** [comment]
Thanks Lukas.
I use Tango 8.1.2 on Ubuntu 14.04
The installed PyTango is 8.1.1 and I want to upgrade to 9

here is the fully information of installation:

rifai@rifai-Inspiron-3458:~/Documents/Program/pytango$ sudo python setup.py install
[sudo] password for rifai: 
running install
running bdist_egg
running egg_info
writing requirements to pytango.egg-info/requires.txt
writing pytango.egg-info/PKG-INFO
writing top-level names to pytango.egg-info/top_level.txt
writing dependency_links to pytango.egg-info/dependency_links.txt
reading manifest file 'pytango.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files found matching 'images'
warning: no previously-included files found matching 'src/precompiled_header.hpp.gch'
writing manifest file 'pytango.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building '_tango' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -DPYTANGO_NUMPY_VERSION="1.13.1" -DPYTANGO_HAS_UNIQUE_PTR=1 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/tango -I/home/rifai/Documents/Program/pytango/ext -I/home/rifai/Documents/Program/pytango/ext/server -I/usr/include/python2.7 -c /home/rifai/Documents/Program/pytango/ext/api_util.cpp -o build/temp.linux-x86_64-2.7/home/rifai/Documents/Program/pytango/ext/api_util.o -std=c++0x
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -DPYTANGO_NUMPY_VERSION="1.13.1" -DPYTANGO_HAS_UNIQUE_PTR=1 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/tango -I/home/rifai/Documents/Program/pytango/ext -I/home/rifai/Documents/Program/pytango/ext/server -I/usr/include/python2.7 -c /home/rifai/Documents/Program/pytango/ext/archive_event_info.cpp -o build/temp.linux-x86_64-2.7/home/rifai/Documents/Program/pytango/ext/archive_event_info.o -std=c++0x
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -DPYTANGO_NUMPY_VERSION="1.13.1" -DPYTANGO_HAS_UNIQUE_PTR=1 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/tango -I/home/rifai/Documents/Program/pytango/ext -I/home/rifai/Documents/Program/pytango/ext/server -I/usr/include/python2.7 -c /home/rifai/Documents/Program/pytango/ext/attr_conf_event_data.cpp -o build/temp.linux-x86_64-2.7/home/rifai/Documents/Program/pytango/ext/attr_conf_event_data.o -std=c++0x
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -DPYTANGO_NUMPY_VERSION="1.13.1" -DPYTANGO_HAS_UNIQUE_PTR=1 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/tango -I/home/rifai/Documents/Program/pytango/ext -I/home/rifai/Documents/Program/pytango/ext/server -I/usr/include/python2.7 -c /home/rifai/Documents/Program/pytango/ext/attribute_alarm_info.cpp -o build/temp.linux-x86_64-2.7/home/rifai/Documents/Program/pytango/ext/attribute_alarm_info.o -std=c++0x
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -DPYTANGO_NUMPY_VERSION="1.13.1" -DPYTANGO_HAS_UNIQUE_PTR=1 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/tango -I/home/rifai/Documents/Program/pytango/ext -I/home/rifai/Documents/Program/pytango/ext/server -I/usr/include/python2.7 -c /home/rifai/Documents/Program/pytango/ext/attribute_dimension.cpp -o build/temp.linux-x86_64-2.7/home/rifai/Documents/Program/pytango/ext/attribute_dimension.o -std=c++0x
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -DPYTANGO_NUMPY_VERSION="1.13.1" -DPYTANGO_HAS_UNIQUE_PTR=1 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/tango -I/home/rifai/Documents/Program/pytango/ext -I/home/rifai/Documents/Program/pytango/ext/server -I/usr/include/python2.7 -c /home/rifai/Documents/Program/pytango/ext/attribute_event_info.cpp -o build/temp.linux-x86_64-2.7/home/rifai/Documents/Program/pytango/ext/attribute_event_info.o -std=c++0x
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -DPYTANGO_NUMPY_VERSION="1.13.1" -DPYTANGO_HAS_UNIQUE_PTR=1 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/tango -I/home/rifai/Documents/Program/pytango/ext -I/home/rifai/Documents/Program/pytango/ext/server -I/usr/include/python2.7 -c /home/rifai/Documents/Program/pytango/ext/attribute_info.cpp -o build/temp.linux-x86_64-2.7/home/rifai/Documents/Program/pytango/ext/attribute_info.o -std=c++0x
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -DPYTANGO_NUMPY_VERSION="1.13.1" -DPYTANGO_HAS_UNIQUE_PTR=1 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/tango -I/home/rifai/Documents/Program/pytango/ext -I/home/rifai/Documents/Program/pytango/ext/server -I/usr/include/python2.7 -c /home/rifai/Documents/Program/pytango/ext/attribute_info_ex.cpp -o build/temp.linux-x86_64-2.7/home/rifai/Documents/Program/pytango/ext/attribute_info_ex.o -std=c++0x
/home/rifai/Documents/Program/pytango/ext/attribute_info_ex.cpp: In function ‘void export_attribute_info_ex()’:
/home/rifai/Documents/Program/pytango/ext/attribute_info_ex.cpp:23:37: error: ‘root_attr_name’ is not a member of ‘Tango::AttributeInfoEx {aka Tango::_AttributeInfoEx}’
  .def_readwrite("root_attr_name",  &Tango::AttributeInfoEx::root_attr_name)
                                     ^
/home/rifai/Documents/Program/pytango/ext/attribute_info_ex.cpp:24:32: error: ‘memorized’ is not a member of ‘Tango::AttributeInfoEx {aka Tango::_AttributeInfoEx}’
  .def_readwrite("memorized",  &Tango::AttributeInfoEx::memorized)
                                ^
/home/rifai/Documents/Program/pytango/ext/attribute_info_ex.cpp:25:34: error: ‘enum_labels’ is not a member of ‘Tango::AttributeInfoEx {aka Tango::_AttributeInfoEx}’
  .def_readwrite("enum_labels",  &Tango::AttributeInfoEx::enum_labels)
                                  ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
rifai@rifai-Inspiron-3458:~/Documents/Program/pytango$

**Comment by LJBD** [comment]
Unfortunately you cannot use PyTango 9 with Tango 8.
The general rule, [as stated in the `README` of PyTango](https://github.com/tango-controls/pytango/blob/develop/README.rst#requirements) is that if you have Tango version `x.y.z`, you can only have PyTango `x.y.w` - the major and minor version numbers have to match.
Please consider upgrading to Tango 9.2.x as well if you want to have the most recent PyTango.

**Comment by hasrifa2003** [comment]
Thank you.

**Comment by LJBD** [comment]
@hasrifa2003 - can we close the issue?

**Comment by hasrifa2003** [comment]
OK. Thanks.
