### ISSUE TITLE
simultaneous events corrupt event_data

### ISSUE THREAD

**Issue by jkotan** [tango-controls/pytango#147]
Hi,

during my stress tests with sardana  https://github.com/sardana-org/sardana/issues/447
I found that when I emits EventType.CHANGE_EVENT events of DevEncoded attribute:

    import PyTango
    from taurus.core.util.codecs import CodecFactory
    
    def cb(event_data):
        if event_data.err:
            print "event error"
            return
        w = CodecFactory().decode(event_data.attr_value.value)

    door = PyTango.DeviceProxy("door/stretch-jk/1")

    while True:
        id_ = door.subscribe_event("RecordData", PyTango.EventType.CHANGE_EVENT, cb, stateless=True)
        door.unsubscribe_event(id_)

for a very few  cases `event_data` is changed by `pytango/tango`. 
I run test with PyTango 9.2.1  and 9.2.0 (tango 8.2.5a)  on stretch and jessie getting similar issues.
I've not manged to check it with the develop branch of  PyTango because of  https://github.com/tango-controls/pytango/issues/144
Error appears when I run simultaneously many clients subscribed to the same attribute. 

In order to check it  I added print-outs in
1)  `void __set_value(...)` in `val_real` of `ext/server/attribute.cpp` indirectly called by `read_RecordData` 
2)  `update_value_as_string<Tango::DEV_ENCODED>(...)` in `r_ch_ptr` of `ext/device_attribute.cpp` called during creating event_data which is read by callback method.

In the most cases for the corresponding calls the data were equal but I get also cases where
a few bytes  of long encoded data records of  `r_ch_ptr` were overwritten at the end or at the begining e.g.
a)

    val_real[-10:] =  '\xdc\x91N\x14$\x11=\x914\x00'
    r_ch_ptr[-10:] =  '\xdc\x91N\x90-\x00\x00\x00\x00\x00'

b)

    val_real[-10:] =  '\xb9"\x9c(H&C\xf0\x89\x80'
    r_ch_ptr[-10:] =  '\xb9"\x9c(H&C\x80-\x00'

c) 
 
    val_real[:20] = 'BZh91AY&SYy\x18\x1ci\x00C\xc8\x7f\xff\xff'
    r_ch_ptr[:20] = '\xce\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1ci\x00C\xc8\x7f\xff\xff'

For 9.2.0 I get also the cases where whole long data_event value was filled with '\x00' characters.
In my test case since the data is pickled during decoding data I get `IOError: invalid data stream` but I can imaging that for other cases user may even not notice that the data is corrupted.

Therefore I would like to ask if someone account  a similar problem.

Best regards,
Jan

**Comment by vxgmichel** [comment]
#144 is now fixed on `develop` if you want to give `9.2.2` a try.

**Comment by jkotan** [comment]
Thanks. During running the same test scripts for the develop branch I have another problem, 

    Traceback (most recent call last):
      File "./my5.py", line 23, in <module>
        door.unsubscribe_event(id_)
      File "/home/jkotan/testinst2/lib/python2.7/site-packages/pytango-9.2.2.dev0-py2.7-linux-x86_64.egg/tango/green.py", line 182, in greener
        return executor.run(fn, args, kwargs, wait=wait, timeout=timeout)
      File "/home/jkotan/testinst2/lib/python2.7/site-packages/pytango-9.2.2.dev0-py2.7-linux-x86_64.egg/tango/green.py", line 96, in run
        return fn(*args, **kwargs)
      File "/home/jkotan/testinst2/lib/python2.7/site-packages/pytango-9.2.2.dev0-py2.7-linux-x86_64.egg/tango/device_proxy.py", line 1285, in __DeviceProxy__unsubscribe_event
        raise KeyError("This device proxy does not own this subscription " + str(event_id))

i.e. `subscribe_event()` return `None` instead of `event_id`.

**Comment by vxgmichel** [comment]
Thank you for the report, I found the problem: 71236c9d

I'm working on a fix now.

**Comment by vxgmichel** [comment]
@jkotan #149 should fix the intermediate issue you reported, feel free to give `develop` another try.

**Comment by jkotan** [comment]
I also get the same error with  the `develop` branch.

**Comment by jkotan** [comment]
I've added another printouts in 

    static void _push_event(PyCallBackPushEvent* self, OriginalT * ev)

in `callback.cpp` for `OriginalT = EventData` 

of 

    ((ev->attr_value)->get_Encoded_data()).inout()[0].encoded_data

before converting it to python and it looks corrupted as well (in the cases I get the problem).
So maybe it is not a problem with `pytango` but in `cppTango`.

**Comment by jkotan** [comment]
Hi,

it looks like this bug is caused by the fact that `Attribute.set_value(encoded_format, encoded_data)` for DevEncoded copies  only the pointer to the `encoded_data`.

Thus, if `encode_data` is a local variable and will be removed by `gc` the "stored" data for the attribute may be overwritten by something else.  Therefore, it would be good to increase reference counter for `encoded_data` on `set_value()` and decrease it back when is no more needed (new data is set).

I think similar issue was fixed some time ago for setting status?/state? of tango servers.

**Comment by tiagocoutinho** [comment]
Thanks for the report @jkotan .I agree with you. It is coming from `Attribute.set_value`. The technical problem is that tango (well, actually CORBA) does not tell when it doesn't need the memory.

The lazy solution would be to do a copy and pass it to tango saying it should manage de pointer.

Fortunately I think the problem has already been solved for the SPECTRUM and IMAGE without copying data by using a boost borrowed reference.

Just wanted to give you some feedback. Before I talk more I need to have a better look to see how I can come up with a solution.

**Comment by jkotan** [comment]
Hi Tiago,

Thanks for your confirmation. Is there any movement in fixing the bug?

I've just found that this bug may also cause instabilities of limaccd, i.e. in LimaCCDs.py we have DevEncoded attributes like 'last_image'  or 'video_last_image' which are set from local python variables in their read_* methods. 
So this bug may be one of reasons of LimaCCD problems.
But contrary to Sardana/Taurus case image is not automatically decoded so user may not noticed that he/she reads faked image,unless he/she get a crash or seg fault.

Bests,
Jan
