### ISSUE TITLE
problem with compile Boost.Python on windows 10 64bit

### ISSUE THREAD

**Issue by Kamil2806** [tango-controls/pytango#150]
Hi,

When installing Boost.Python, I get "fatal errors" when compiling a sample program. All the steps you will look like are:
1. I install Microsoft Visual C ++ Compiler for python 2.7
2. I pick and install "boost_1_64_0-msvc-14.1-64.exe" from:
https://sourceforge.net/projects/boost/files/boost-binaries/1.64.0/
3. I put environment variable to boost root directory (in my case: C:\local\boost_1_64_0)
4. Open the command prompt and change my current directory to the root directory boost. Then, type the following commands:
- bootstrap
- . \b2
5. I get "boost-jam-3.1.18.zip" from https://sourceforge.net/projects/boost/files/boost-jam/3.1.18/ and put it in the boost root directory.
6. Open command promt and change my current directory to the boost root directory and invoke bjam as follows:
bjam toolset=msvc --build-type = complete stage
7. Go to the libs /python /example /quickstart directory of my Boost installation (where is my sample program) and invoke: 
bjam toolset=msvc --verbose-test test
8. At the end of compilation, Command promt shows sth like this on the picture. I mean the "fatal error". 

![image](https://user-images.githubusercontent.com/30506397/28686011-15ec30ee-730a-11e7-9157-ae50303a6049.png)

Therefore I would like to ask if someone account a similar problem.

Best regards,
Kamil

**Comment by vxgmichel** [comment]
Hi @Kamil2806, 

As far as I understand, building pytango for windows is very tricky. @NexeyaSGara might be able to help you though. In any case, you can find windows binaries for pytango 9.2.1 on [PyPi](https://pypi.python.org/pypi/PyTango/9.2.1).

**Comment by LJBD** [comment]
A quick remark: `No such file or directory` might mean that you don't have proper include paths setup. Have you double-checked that?

**Comment by Kamil2806** [comment]
Hi @vxgmichel,

I already installed pytango using PyPi but my only problem is that i can't compile it :( Anyway thank you for help.

**Comment by Kamil2806** [comment]
Hi @LJBD,
I checked it even three times but i am sure that the files are there. So I don't know why there is that problem.

**Comment by vxgmichel** [comment]
@Kamil2806 
> I already installed pytango using PyPi but my only problem is that i can't compile it

You won't need to compile anything if you use the [windows installer](https://pypi.python.org/packages/9e/5b/0f953e8b7f5fd040eeb5d433b0c381926e008327d5ccf787498706fdaf60/pytango-9.2.1.win-amd64-py2.7.msi#md5=0c07c025f936b9594498fd77a3686b1a).

**Comment by NexeyaSGara** [comment]
Did you set PYTHONPATH ?
I think this can be the solution

**Comment by Kamil2806** [comment]
@vxgmichel 
I thought like you before i tried to run the sample program and i needed "boost-jam" but the installer did not provide this tool.

**Comment by Kamil2806** [comment]
@NexeyaSGara 
Mean you that i should set path to my python installation to PYTHONPATH ?

**Comment by NexeyaSGara** [comment]
@Kamil2806 yes

**Comment by vxgmichel** [comment]
@Kamil2806 

I guess you also need the [boost binaries](https://sourceforge.net/projects/boost/files/boost-binaries/) (though I'm no windows expert).

**Comment by Kamil2806** [comment]
@NexeyaSGara 
I did like you said, but it doesn't work. Maybe i did something wrong. So this is how i did it:
![image](https://user-images.githubusercontent.com/30506397/28781413-41ab3e84-760a-11e7-8bd5-75099d7dee2a.png)

**Comment by Kamil2806** [comment]
@vxgmichel 
Unfortunately, I already have this package and it don't resolve the problem :/

**Comment by NexeyaSGara** [comment]
@Kamil2806 seems ok, did you had the same error ?

**Comment by Kamil2806** [comment]
@NexeyaSGara 
Yes, I checked it once again and this is exactly the same problem.

**Comment by NexeyaSGara** [comment]
@Kamil2806 ok.

Try to set BOOST_ROOT

**Comment by Kamil2806** [comment]
@NexeyaSGara 
I set BOOST_ROOT but it doesn,t works too.
![image](https://user-images.githubusercontent.com/30506397/28782402-4a6991da-760d-11e7-8bbc-554ee854103e.png)

**Comment by vxgmichel** [comment]
@Kamil2806 

> I thought like you before i tried to run the sample program

What sample program? What kind of error do you get?

**Comment by NexeyaSGara** [comment]
@Kamil2806 
if you have the same error, did you close and reopen the terminal to be sure that env variables are updated ?

**Comment by Kamil2806** [comment]
@vxgmichel 
I use instruction from: http://www.boost.org/doc/libs/1_39_0/libs/python/doc/building.html 
and there is said that to checked everything, you can compile this sample program. The error which i Get is the same like I showed on picture on the top this side. I mean the two "fatal error".

**Comment by Kamil2806** [comment]
@NexeyaSGara 
of course, i close and open command prompt every time when i change something in environment variables.

**Comment by NexeyaSGara** [comment]
@Kamil2806 really strange, beacause your fatal errors are clearly a missing path problem

**Comment by vxgmichel** [comment]
@Kamil2806 
As far as I understand, no building is required to install pytango on windows. The pytango and boost binaries should be enough to be able to import and use the tango module. @NexeyaSGara Can you confirm?

**Comment by NexeyaSGara** [comment]
Normally, yes.

@Kamil2806 did you try to just launch a python command line and type "import tango" ?

**Comment by Kamil2806** [comment]
@NexeyaSGara  @vxgmichel 
Yes, and it's work but if i run some program then i can't compile it.

**Comment by vxgmichel** [comment]
@Kamil2806 It seems like you your tango/pytango installation is working fine then. Can we close this issue?

**Comment by Kamil2806** [comment]
@vxgmichel @NexeyaSGara 
Ok, then I still try resolved this problem with program compiling. Anyway thank you for your help.

**Comment by vxgmichel** [comment]
@Kamil2806 
Good luck with that!
