### ISSUE TITLE
Attribute's fget don't accept functools.partial

### ISSUE THREAD

**Issue by stanislaw47** [tango-controls/pytango#151]
Hi, I've been using PyTango for a while and I've found an error. In my device, there's a list. I want my attributes to read values from that list. Since there's a lot of them, I've decided to use `functools.partial` and `fget` parameter to write less code. Example: 
```python
from tango.server import Device, attribute
from functools import partial


class MyDevice(Device):

    my_list = [5, 10]

    def read_from_list(self, index):
        return self.my_list[index]

    read_first_attr = partial(read_from_list, index=0)

    FirstAttribute = attribute(
        dtype=float,
        fget="read_first_attr"
    )

    read_second_attr = partial(read_from_list, index=1)

    SecondAttribute = attribute(
        dtype=float,
        fget="read_second_attr"
    )
```

However, when I try to do that, I receive this execption:
```condole
cf71aecf86b9:python -u /opt/project/adam/example.py
Traceback (most recent call last):
  File "/opt/project/adam/example.py", line 5, in <module>
    class MyDevice(Device):
  File "/usr/lib64/python2.7/site-packages/tango/server.py", line 534, in __new__
    _init_tango_device_klass(cls, dct)
  File "/usr/lib64/python2.7/site-packages/tango/server.py", line 475, in _init_tango_device_klass
    tango_device_klass, attrs=attrs)
  File "/usr/lib64/python2.7/site-packages/tango/server.py", line 437, in __create_tango_deviceclass_klass
    __patch_attr_methods(tango_device_klass, attr_obj)
  File "/usr/lib64/python2.7/site-packages/tango/server.py", line 213, in __patch_attr_methods
    __patch_read_method(tango_device_klass, attribute)
  File "/usr/lib64/python2.7/site-packages/tango/server.py", line 151, in __patch_read_method
    read_attr = _get_wrapped_read_method(attribute, read_method)
  File "/usr/lib64/python2.7/site-packages/tango/server.py", line 98, in _get_wrapped_read_method
    read_args = inspect.getargspec(read_method)
  File "/usr/lib64/python2.7/inspect.py", line 815, in getargspec
    raise TypeError('{!r} is not a Python function'.format(func))
TypeError: <functools.partial object at 0x2d41628> is not a Python function

Process finished with exit code 1
```
 It looks like `functools.partial` is not a function and thus, it's not possible to assign it to `fget`. Of course, I can workaround this by defining function just to read that one attribute... but this is what I want to avoid. It would be more pythonic to be able to do this, since there would be no need to type bunch of excessive code.

**Comment by vxgmichel** [comment]
Thank you for your report! I also think it's something that should be fixed.

Do you want to work on a PR? I'll be happy to review it.

**Comment by stanislaw47** [comment]
Yes, I'd like to. I guess it's just a minor fix, shouldn't take long. I'll probably start new branch next week.

**Comment by johanfforsberg** [comment]
While I agree that this should be fixed anyway, I've solved a similar problem by doing something like this:
```python
index_lookup = {"FirstAttribute": 0, "SecondAttribute": 1}

def read_my_attr(self, attr):
    index = self.index_lookup[attr.get_name()]
    ...

FirstAttribute = attribute(
        dtype=float,
        fget="read_my_attr"
)

SecondAttribute = attribute(
        dtype=float,
        fget="read_my_attr"
)
```

**Comment by AntoineDupre** [comment]
Hi,

I started to implement a fix in PR #154 using simple closures instead of functools.wraps (not compatible with functools.partial), @stanislaw47 fill free to update this PR, change everything or add the missing features (like fset and isinstance).

**Comment by stanislaw47** [comment]
Hi,
@AntoineDupre, I'm happy to work on that PR

**Comment by stanislaw47** [comment]
I've tried to perform `git push` to branch `issue-151` but it has failed. After little investigation, I believe I don't have write access to this repo/branch. Can you help me with that, @AntoineDupre?
