### ISSUE TITLE
pytango compilation problems

### ISSUE THREAD

**Issue by jkotan** [tango-controls/pytango#152]
Hi,

Trying from the scratch to compile/install `tango-idl` `cppTango` (master) and `pytango` (develop) on `jessie` the commands

    python setup.py build --no-doc

gave me the following error

    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DPYTANGO_NUMPY_VERSION="1.8.2" -DPYTANGO_HAS_UNIQUE_PTR=1 -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/home/jkotan/testtango/include -I/home/jkotan/sources/pytango/ext -I/home/jkotan/sources/pytango/ext/server -I/usr/include/python2.7 -c /home/jkotan/sources/pytango/ext/device_data.cpp -o build/temp.linux-x86_64-2.7/home/jkotan/sources/pytango/ext/device_data.o -std=c++0x
    In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1761:0,
		     from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:17,
		     from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
		     from /home/jkotan/sources/pytango/ext/tango_numpy.h:26,
		     from /home/jkotan/sources/pytango/ext/from_py.h:24,
		     from /home/jkotan/sources/pytango/ext/pytgutils.h:19,
		     from /home/jkotan/sources/pytango/ext/device_data.cpp:13:
    /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^
    In file included from /home/jkotan/sources/pytango/ext/from_py.h:22:0,
		     from /home/jkotan/sources/pytango/ext/pytgutils.h:19,
		     from /home/jkotan/sources/pytango/ext/device_data.cpp:13:
    /home/jkotan/sources/pytango/ext/device_data.cpp: In function ‘boost::python::api::object PyDeviceData::extract(boost::python::api::object, PyTango::ExtractAs)’:
    /home/jkotan/sources/pytango/ext/tgutils.h:234:73: error: ‘DOIT_ARRAY’ was not declared in this scope
     #define __TANGO_DVBA __TANGO_DEPEND_ON_TYPE_AUX_ID(DEVVAR_BOOLEANARRAY, DOIT_ARRAY)
									     ^
    /home/jkotan/sources/pytango/ext/tgutils.h:176:9: note: in definition of macro ‘__TANGO_DEPEND_ON_TYPE_AUX_ID’
	     DOIT; \
	     ^
    /home/jkotan/sources/pytango/ext/tgutils.h:264:9: note: in expansion of macro ‘__TANGO_DVBA’
	     __TANGO_DVBA \
	     ^
    /home/jkotan/sources/pytango/ext/device_data.cpp:196:9: note: in expansion of macro ‘TANGO_DO_ON_DEVICE_DATA_TYPE_ID’
	     TANGO_DO_ON_DEVICE_DATA_TYPE_ID(self.get_type(),
	     ^
    /home/jkotan/sources/pytango/ext/tgutils.h:175:27: warning: unused variable ‘tangoTypeConst’ [-Wunused-variable]
	     static const long tangoTypeConst = Tango:: typename_; \
			       ^
    /home/jkotan/sources/pytango/ext/tgutils.h:234:22: note: in expansion of macro ‘__TANGO_DEPEND_ON_TYPE_AUX_ID’
     #define __TANGO_DVBA __TANGO_DEPEND_ON_TYPE_AUX_ID(DEVVAR_BOOLEANARRAY, DOIT_ARRAY)
			  ^
    /home/jkotan/sources/pytango/ext/tgutils.h:264:9: note: in expansion of macro ‘__TANGO_DVBA’
	     __TANGO_DVBA \
	     ^
    /home/jkotan/sources/pytango/ext/device_data.cpp:196:9: note: in expansion of macro ‘TANGO_DO_ON_DEVICE_DATA_TYPE_ID’
	     TANGO_DO_ON_DEVICE_DATA_TYPE_ID(self.get_type(),
	     ^
    /home/jkotan/sources/pytango/ext/device_data.cpp: In function ‘void PyDeviceData::insert(Tango::DeviceData&, long int, boost::python::api::object)’:
    /home/jkotan/sources/pytango/ext/tgutils.h:234:73: error: ‘DOIT_ARRAY’ was not declared in this scope
     #define __TANGO_DVBA __TANGO_DEPEND_ON_TYPE_AUX_ID(DEVVAR_BOOLEANARRAY, DOIT_ARRAY)
									     ^
    /home/jkotan/sources/pytango/ext/tgutils.h:176:9: note: in definition of macro ‘__TANGO_DEPEND_ON_TYPE_AUX_ID’
	     DOIT; \
	     ^
    /home/jkotan/sources/pytango/ext/tgutils.h:264:9: note: in expansion of macro ‘__TANGO_DVBA’
	     __TANGO_DVBA \
	     ^
    /home/jkotan/sources/pytango/ext/device_data.cpp:206:9: note: in expansion of macro ‘TANGO_DO_ON_DEVICE_DATA_TYPE_ID’
	     TANGO_DO_ON_DEVICE_DATA_TYPE_ID(data_type,
	     ^
    /home/jkotan/sources/pytango/ext/tgutils.h:175:27: warning: unused variable ‘tangoTypeConst’ [-Wunused-variable]
	     static const long tangoTypeConst = Tango:: typename_; \
			       ^
    /home/jkotan/sources/pytango/ext/tgutils.h:234:22: note: in expansion of macro ‘__TANGO_DEPEND_ON_TYPE_AUX_ID’
     #define __TANGO_DVBA __TANGO_DEPEND_ON_TYPE_AUX_ID(DEVVAR_BOOLEANARRAY, DOIT_ARRAY)
			  ^
    /home/jkotan/sources/pytango/ext/tgutils.h:264:9: note: in expansion of macro ‘__TANGO_DVBA’
	     __TANGO_DVBA \
	     ^
    /home/jkotan/sources/pytango/ext/device_data.cpp:206:9: note: in expansion of macro ‘TANGO_DO_ON_DEVICE_DATA_TYPE_ID’
	     TANGO_DO_ON_DEVICE_DATA_TYPE_ID(data_type,
	     ^
    In file included from /home/jkotan/testtango/include/tango/client/devapi.h:32:0,
		     from /home/jkotan/testtango/include/tango/client/dbapi.h:32,
		     from /home/jkotan/testtango/include/tango.h:93,
		     from /home/jkotan/sources/pytango/ext/pytgutils.h:15,
		     from /home/jkotan/sources/pytango/ext/device_data.cpp:13:
    /home/jkotan/testtango/include/tango/server/tango_const.h: At global scope:
    /home/jkotan/testtango/include/tango/server/tango_const.h:1107:19: warning: ‘Tango::CONF_TYPE_EVENT’ defined but not used [-Wunused-variable]
     const char *const CONF_TYPE_EVENT     = EventName[ATTR_CONF_EVENT];
		       ^
    /home/jkotan/testtango/include/tango/server/tango_const.h:1108:19: warning: ‘Tango::DATA_READY_TYPE_EVENT’ defined but not used [-Wunused-variable]
     const char* const DATA_READY_TYPE_EVENT    = EventName[DATA_READY_EVENT];
		       ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

If anyone knows what is going on?

Bests ,
Jan

**Comment by grm84** [comment]
__TANGO_DVBA was added  to provide backward compatibility as boolean arrays are not supported fully in the c++ library upto and including 9.2.5.
The definition should be protected by
`#if TANGO_VERSION_NB > 90205`

**Comment by vxgmichel** [comment]
The current tango version on the `cppTango` master branch is [10.0.1](https://github.com/tango-controls/cppTango/blob/master/CMakeLists.txt#L7-L9).

As a general rule, `libtango` and `pytango` should share the same major and minor version (for a version `X.Y.Z`, `X` and `Y` should match).

**Comment by jkotan** [comment]
Ah, indeed.Thanks
