### ISSUE TITLE
No module named _tango

### ISSUE THREAD

**Issue by stanislaw47** [tango-controls/pytango#156]
Hi, I've been trying to build a Docker image for installing PyTango from sources. Image do build, PyTango do install but when try to `import tango` i get this:
```python
>>> import tango
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tango/__init__.py", line 137, in <module>
    from ._tango import (
ImportError: No module named _tango
```

Frankly, I have virtually no idea what I'm doing wrong. I'd appreciate any help.
Here are mine [Dockerfile](https://www.dropbox.com/s/1f063qfs8oo8sk2/Dockerfile.txt?dl=0), image build [log](https://www.dropbox.com/s/h2ea3q8tcc6vz8d/build.txt?dl=0) and PyTango installation [log](https://www.dropbox.com/s/covkwtytzpeeesb/install.txt?dl=0)

**Comment by andygotz** [comment]
Hi, frankly I am not an expert in Docker or PyTango either so I can only give you some hints. From the install log it looks like PyTango.9.2.2 was installed correctly for python 2.7. Are you sure you are trying to import tango from a python 2.7 shell? Is PyTango installed where it said it would i.e. /usr/lib/python2.7/site-packages.  Make sure the shared library module _tango.blablabla.so is in this directory and that LD_LIBRARY_PATH includes this directory. Some simple suggestions.

**Comment by vxgmichel** [comment]
Hi @stanislaw47,

I think the issue here is that you're trying to import `tango` from the root of the pytango repo. Instead of importing tango from your freshly installed package, python tries to import from the local `tango` directory.

You might also want to split the `RUN` step of your dockerfile into several steps so docker can build intermediary images.

Hope that helps,
Cheers

**Comment by stanislaw47** [comment]
Hi @vxgmichel 
Thank you for your advice, you're totally right! When I opened Python shell in a different directory, `import tango` went smoothly.
