### ISSUE TITLE
PyTango 9.2.2 branch does not compile in windows

### ISSUE THREAD

**Issue by mike-a-smith** [tango-controls/pytango#160]
In device_impl.cpp, push_pipe_event() function definition:

- gettimeofday() function is called which does not exist in windows

```
    	struct timeval tv;
    	gettimeofday(&tv, NULL);
    	bool reuse = false;
	PyDevicePipe::set_value(dpb, pipe_data);
    	self.push_pipe_event(__pipe_name, &dpb, tv, reuse);

```

**Comment by vxgmichel** [comment]
Thanks for your report, it's fixed and will appear in the 9.2.2 release.
