### ISSUE TITLE
error importing Tango on windows

### ISSUE THREAD

**Issue by PhilLAL** [tango-controls/pytango#167]
Hello,
I would like to install a Windows Tango client.
After installing 64bits MSI file on windows 7 Pro SP1 64bits, I launched python.

When importing tango, I got the following error : 
̀
```
1> import tango
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-8235b14f820c> in <module>()
----> 1 import tango

C:\Python27\Lib\site-packages\tango\__init__.py in <module>()
    119         # in windows try to find the location for tango
    120         __prepare_nt()
--> 121         from . import _tango
    122 else:
    123     from . import _tango

ImportError: DLL load failed: %1 nÆest pas une application Win32 valide. [translation : is not a valid Win32 application]

```
I probably forgot something but I am not very experienced with windows.  
Do you have any idea what I forgot?
Thank you

**Comment by vxgmichel** [comment]
Thanks for the report, @NexeyaSGara any idea?

**Comment by NexeyaSGara** [comment]
Hi,

I think that it search TANGO_ROOT environment variable.

**Comment by vxgmichel** [comment]
@NexeyaSGara I thought TANGO_ROOT was only for the build, is that right?

In this case, @PhilLAL installed the binaries, so there should be no configuration required right?

**Comment by NexeyaSGara** [comment]
In fact, this is needed for finding the tango.dll if it's hasn't got found in classical "program files"

**Comment by PhilLAL** [comment]
Hi, thank you @NexeyaSGara 
To install my dev client, I got "TANGO 9.2.2 libraries for Windows 64 bits and Visual Studio 2010 (VC10)" from http://www.tango-controls.org/downloads/binary/ and I unzipped it, I then installed python(x,y) and pytango from MSI found on https://pypi.python.org/pypi/PyTango/9.2.1
I then set TANGO_ROOT to this directory (C:\Program Files\tango922_win64_vc10\lib\vc10_dll) but I still got the same error message.


note: there is no tango.dll into the directory but tango922.dll and tango922d.dll.

**Comment by NexeyaSGara** [comment]
@PhilLAL 
For now, pytango is expecting to find tango  in
%TANGO_ROOT%\arch\lib\vc

So I think you will have to change the directory structure to have the dll in :

c:\Program files\tango_922\win64\lib\vc10_dll

I personnaly used the vc12 installer for tango, any reason to stay on vc10 ?

**Comment by PhilLAL** [comment]
@NexeyaSGara : I rename the directory but it is still a failure. 
I use this vc10 since this is the most recent I found, but I can switch to vc12 if you let me know where to find it. I do not find anything newer than vc_10 on the tango page http://www.tango-controls.org/downloads/binary/

**Comment by NexeyaSGara** [comment]
ok
Let's try with 
https://sourceforge.net/projects/tango-cs/files/TangoSetup-9.2.2_win64.exe/download

I use this setup and the same msi for pytango and it was working (on a training last week)

**Comment by PhilLAL** [comment]
Ok, just to be sure, do you confirm this is a complete tango installation and not just the libraries? 
Here are the steps I followed:
- uninstallation of pytango
- installation of https://sourceforge.net/projects/tango-cs/files/TangoSetup-9.2.2_win64.exe/download
- installation of pytango MSI (http://pypi.python.org/packages/2.7/P/PyTango/PyTango-8.0.2.win32-py2.7.msi)
- changingTANGO_ROOT to "c;\program Files\tango" 
- launching python and "import PyTango"

However, I still got the same Win32 error. :(

**Comment by NexeyaSGara** [comment]
@PhilLAL 
https://pypi.python.org/packages/fe/6e/8780412c9b04ba49177032b792e35c0461c1da49b3e204badf817bba23ec/pytango-9.2.1.Win32-py2.7.msi#md5=668c63b09c058225ad377a2ab75f43ee

this one

**Comment by PhilLAL** [comment]
copied the wrong path, I used in fac https://pypi.python.org/packages/9e/5b-/0f953e8b7f5fd040eeb5d433b0c381926e008327d5ccf787498706fdaf60/pytango-9.2.1.win-amd64-py2.7.msi#md5=0c07c025f936b9594498fd77a3686b1a (which is AMD64 MSI since our system is a Windows 7 Pro SP1 64bits).
Do you think we should use win32 MSI?

When uninstalling amd64 PyTango and installing win32 PyTango MSI, and than importing PyTango, we got this error: "RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9"
NumPy 1.9.2-8 was installed through Python(x,y) 2.7.10.0 (suggested for taurus installation steps)

**Comment by PhilLAL** [comment]
Since it seems version 1.9 is not enough, we installed 1.13 through "python -m pip install --upgrade"
PyTango worked!
Thank you for your help.

I do not know very well Windows but I am a bit  confused to have to install win32 version of PyTango. Does anyone know why we have to do this?

**Comment by NexeyaSGara** [comment]
I don't think it's mandatory.

I think if you try back with the 64 version it musts works too.

**Comment by PhilLAL** [comment]
We ran some tests again but 64bits and 32bits do not returns same result.
Here are some screenshots:
- win-amd64 exe
![win-amd64 exe](https://owncloud.lal.in2p3.fr/index.php/s/Gkptyk2pokCYypg/download)
- win-amd64 msi
![win-amd64 msi](https://owncloud.lal.in2p3.fr/index.php/s/UMzPg7JAJK6N2dg/download)
- win32 exe
![win32 exe](https://owncloud.lal.in2p3.fr/index.php/s/nWUDNKft9PbaQLO/download)
- win32 msi
![win32 msi](https://owncloud.lal.in2p3.fr/index.php/s/MZME3iKj20pOVtd/download)

I imagine this could be due to a 32 bits version of python(x,y) (I do not remember any choice between 32 and 64bits).
