### ISSUE TITLE
Async mode server: dynamic attribute read/write/is_allowed are not called by worker

### ISSUE THREAD

**Issue by tiagocoutinho** [tango-controls/pytango#173]
In async mode (gevent, asyncio, ...) the *dynamic attributes* read, write and is_allowed methods are not called through the worker like the *standard attributes*

**Comment by mliszcz** [comment]
Probably got the same issue:
```
sys:1: RuntimeWarning: coroutine 'AsyncioDevice.getter' was never awaited
```

As a workaround I needed to decorate my methods:
```python
def run_in_executor(fn):
    @functools.wraps(fn)
    def wrapper(*args, **kwargs):
        get_worker().execute(wrapper, *args, **kwargs)
    return wrapper
```

Howeve it would be nice to have this handled by PyTango.

**Comment by stanislaw55** [comment]
Hi
I just hit this issue. Is there any chance that it will be fixed any time soon?

**Comment by ajoubertza** [comment]
Hi @stanislaw55 

I wasn't planning on working on this.  Would you consider helping by submitting a pull request?

**Comment by stanislaw55** [comment]
Hi @ajoubertza 
Actually, I would like to make time for contribution but the fix proposed by @mliszcz did not worked for me for some reason. I did not investigated in depth since docs mentioned experimental state of server GreenMode. However, now I will come back to this issue and try to generate more detailed bug report.

My setup:
pytango 9.2.5
Libtango 9.2.5
Python 3.6.8

I did not tested this fix with (Py)Tango 9.3.x because of lack of such libraries compiled. However, I'll try to test it and maybe latest version from develop. 

Stay tuned!

**Comment by stanislaw55** [comment]
Okay, that was quick one

The fix that worker for me
```python
import functools

from tango.server import get_worker

def run_in_executor(fn):
    @functools.wraps(fn)
    def wrapper(*args, **kwargs):
        get_worker().execute(fn, *args, **kwargs)
    return wrapper
```
(mind that now in `execute` call there's `fn`, not `wrapper`)

**Comment by ajoubertza** [comment]
@stanislaw55 Well spotted - the `fn` makes more sense than a recursive call!

If you're working on a PR, I suggest starting by adding one or more failing tests at the end of https://github.com/tango-controls/pytango/blob/develop/tests/test_server.py.  I see there are actually no tests for is_allowed!  

You could base them on something like the one below.  The `typed_values` fixture will repeat the test for lots of different types of attributes.  The `server_green_mode` will repeat the test for all the different green modes.

https://github.com/tango-controls/pytango/blob/fa1193e2d63e957e16940931a31eb90ca267c353/tests/test_server.py#L153-L171

If you explicitly need `async` or `await` keywords in the test, you have to jump through some hoops to keep the code readable in Python versions prior to 3.5.
https://github.com/tango-controls/pytango/blob/fa1193e2d63e957e16940931a31eb90ca267c353/tests/test_server.py#L383-L391

**Comment by stanislaw55** [comment]
Thanks for detailed instrution on test, @ajoubertza!

I'll try to make some time for PR in days to come
