### ISSUE TITLE
DeviceAttribute can't be used in await expression

### ISSUE THREAD

**Issue by hardion** [tango-controls/pytango#186]
The example using asyncio (https://pytango.readthedocs.io/en/latest/green_modes/green.html) is reporting an error when reading the attribute.

>>> sys/tg_test/1/double_scalar
object DeviceAttribute can't be used in 'await' expression

My aim is to use AttributeProxy in the python REST implementation in order to manage a cache.
My environment is conda with python 3.5 and PyTango 9.2.2

**Comment by hardion** [comment]
Find another object that can't be await: object AttributeInfoEx from Device.get_attribute_config.
Should I open a new issue or rename the title to "Extend the asyncio to ..."?

**Comment by vxgmichel** [comment]
Hi Vincent!

> The example using asyncio is reporting an error when reading the attribute.

Thanks for the report, 02d17db should fix that.

> Find another object that can't be await: object AttributeInfoEx from Device.get_attribute_config.

This should get fixed with PR #187.

**Comment by vxgmichel** [comment]
Hi @hardion, would you like the review PR #187?

**Comment by vxgmichel** [comment]
Merged, will become visible in v9.2.3.
