### ISSUE TITLE
PyTango build

### ISSUE THREAD

**Issue by stanislaw55** [tango-controls/pytango#189]
Hi,
I've been trying to build PyTango from sources in debug mode. I've found variable `please_debug` in `setup.py` so I just changed it value to `True` and typed `python setup.py install`. However, it did not succeed, printing errors below. I'm using:
* CentOS 7
* `boost-devel` and `boost-python` in versions 1.53
* `numpy` 1.14.2

I don't know if it's relevant but I'm also using Tango C++ kernel compiled in debug mode

See the errors [here](https://pastebin.com/UHzrB2UW).

**Comment by vxgmichel** [comment]
Hi @stanislaw55,

I'm sorry but I've never used the debug mode and don't have time to investigate this issue at the moment.

You could try with the conda environment we use in [our CI](https://github.com/tango-controls/pytango/blob/develop/.travis.yml) to see if it gets you any further.

**Comment by jairomoldes** [comment]
I was able to compile "stable" (9.2.4) and "develop" (9.2.5) with "please_debug = True" on a debian9 machine with no problems.
