### ISSUE TITLE
python 3.7 incompatibilities

### ISSUE THREAD

**Issue by picca** [tango-controls/pytango#202]
Hello,

while looking after the Debian python 3.7 transition, I got errors dring the pytango build process.
like this error

Indeed async is now a reserved work, so, you need to adapt this code :)

Cheers

Frederic
```
setup.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
setup.py:55: DeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5
  distribution = platform.linux_distribution()[0].lower() if POSIX else ""
  File "/usr/lib/python3.7/dist-packages/tango/asyncio_tools.py", line 94
    _chain_future(asyncio.async(coro, loop=loop), future)
                              ^
SyntaxError: invalid syntax

  File "/usr/lib/python3.7/dist-packages/tango/gevent_executor.py", line 127
    watcher = self.hub.loop.async()
                                ^
SyntaxError: invalid syntax
```

**Comment by vxgmichel** [comment]
Hi @picca,

Thanks for your report, I'm on it.

**Comment by vxgmichel** [comment]
Fixed and validated by the CI!

**Comment by picca** [comment]
Is it possible to do a release for this fix ?

**Comment by vxgmichel** [comment]
@picca sure, how urgent is it?

I was thinking about the tango 9.3 bump (since pytango follows libtango major and minor releases).

I'd like to avoid maintaining two branches simultaneously (9.2 and 9.3) so I was planning to wait for libtango 9.3 to be mature enough, release the last 9.2.X version and move on to 9.3.0. So can you wait for this transition or do you need an intermediate 9.2 release?

**Comment by picca** [comment]
How long to wait for this transition ?

**Comment by vxgmichel** [comment]
I guess it'll take few months before libtango 9.3 is ready.

**Comment by picca** [comment]
In that case the best is to provide a 9.2.4 version with this fix... or to provide a patch on top of 9.2.3 and integrate it in the Debian package.

but it would be better to do a small release for everyone and not only Debian.

**Comment by vxgmichel** [comment]
Ok, I'll do that then. Probably not before next week though.

**Comment by picca** [comment]
no problem, this is just that if it takes months it is a problem, because we can not backports anymore all other projects dependening on pytango, since pytango is broken in Debian unstable  and testing.

Thanks a lot

Frederic

**Comment by vxgmichel** [comment]
Hi @picca,

[Version 9.2.4 is on PyPI](https://pypi.org/project/PyTango/9.2.4/) if you want to give it a try :)

**Comment by picca** [comment]
Thanks, I just asked Sandor if he would like to prepare the Debian package.

Cheers
