### ISSUE TITLE
Release 9.2.4

### ISSUE THREAD

**Issue by vxgmichel** [tango-controls/pytango#206]
I'm releasing 9.2.4 a bit sooner than expected, for 2 reasons:
- It fixes a [memory leak in gevent green mode](https://github.com/tango-controls/pytango/issues/192) that was introduced in 9.2.3.
- It provides [python 3.7 compatibility](https://github.com/tango-controls/pytango/issues/202).

Task list:

- [x] Editing the changelog
- [x] Bumping the version
- [x] Merging develop into stable
- [x] Make sure Travis is OK
- [x] Make sure the documentation is updated
- [x] Create a release tag on GitHub
- [x] Upload the new version to PyPI
- [x] Bumping the version with "-dev" in the develop branch
- [x] Fill the release description on GitHub
- [x] Build conda packages
- ~~[ ] Advertise the release on the mailing list~~ the mailing list is down --'

**Comment by ajoubertza** [comment]
Thanks for the new release @vxgmichel

**Comment by vxgmichel** [comment]
No problem! By the way anyone can make a release at any time, so feel free to do so if you need to ;)
