### ISSUE TITLE
RuntimeWarning: greenlet.greenlet size changed

### ISSUE THREAD

**Issue by picca** [tango-controls/pytango#208]
Hello is tis warning message means something for you ?

reading sources... [100%] utilities

/usr/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144, got 128
  return f(*args, **kwds)
/usr/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144, got 128
  return f(*args, **kwds)
/usr/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144, got 128
  return f(*args, **kwds)
/usr/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144, got 128
  return f(*args, **kwds)

**Comment by vxgmichel** [comment]
Hi @picca,

I think it's related to [gevent/gevent#1260](https://github.com/gevent/gevent/issues/1260). Downgrading to greenlet 0.4.13 should fix it.
