### ISSUE TITLE
Missing methods in Documentation

### ISSUE THREAD

**Issue by abdomit** [tango-controls/pytango#217]
It seems that some methods are not present in the official documentation. I don't have an exhaustive list, just an example.

For instance LatestDeviceImpl.poll_command exists and works, but it not in the documentation (https://pytango.readthedocs.io/en/stable/server_api/device.html).

**Comment by vxgmichel** [comment]
Thanks for the report!

`LatestDeviceImpl.poll_command` and `LatestDeviceImpl.poll_attribute` docstrings are missing from the `__doc_DeviceImpl` function:

https://github.com/tango-controls/pytango/blob/4b429e731841590783c86abafc41f93436017424/tango/device_server.py#L770

Here's an example of a documented method:

https://github.com/tango-controls/pytango/blob/4b429e731841590783c86abafc41f93436017424/tango/device_server.py#L789-L798

Is anyone willing to work on this issue?

**Comment by abdomit** [comment]
I tried to see which methods are not in the documentation. So I looked at methods without .\_\_doc\_\_ in PyTango (9.2.4).

init_device is the only one that doesn't have the .\_\_doc\_\_ but is nevertheless in the documentation (I don't fully understand why...).

The missing methods in the documentation seem to be:

tango.Device_5Impl
-
get_attribute_config
get_attribute_config_2
get_attribute_config_3
get_device_class
init_logger
is_attribute_polled
is_command_polled
poll_attribute
poll_command
set_attribute_config_3
start_logging
stop_logging
stop_poll_attribute
stop_poll_command


tango.DeviceClass
-
get_class_attr
get_pipe_by_name
get_pipe_list


tango.Attr
-
check_type
is_allowed has no doc
read
write


tango.Util
-
get_device_ior
get_dserver_ior
init
instance
orb_run
server_cleanup
set_interceptors
set_use_db

I could help by transposing C++ documentation for these methods. However, I am not sure if we really want to have a documentation for all these methods, for instance: get_attribute_config, get_attribute_config_2 and get_attribute_config_3, do we have to document the 3 methods?

Ps: There is a typo in the doc of Device_5Impl.init_device

**Comment by piogor** [comment]
Hi, I (@piogor) may take care of this as part of documentation service. Just need to be added to repo as developer.
