### ISSUE TITLE
Better documentation for exceptions and error access

### ISSUE THREAD

**Issue by jkotan** [tango-controls/pytango#228]
Hi,

in my python3 tests in the code

```python

            except PyTango.CommunicationFailed as cf:                                                                                 
                if len(cf.errors) >= 2 and \                                                                                          
                   cf.errors[1].reason == "API_DeviceTimedOut":                                                                       
                    TangoUtils.wait(apool)                                                                                            
                else:                                                                                                                 
                    raise     
```
I get randomly the following error:

```
  File "/home/jkotan/testinst3/lib/python3.5/site-packages/nxsrecconfig/ProfileManager.py", line 993, in __prepareMntGrp
    mfullname = self.__createMntGrpDevice(mntGrpName, timer)
  File "/home/jkotan/testinst3/lib/python3.5/site-packages/nxsrecconfig/ProfileManager.py", line 851, in __createMntGrpDevice
    if len(cf.errors) >= 2 and \
AttributeError: 'CommunicationFailed' object has no attribute 'errors'
```
It does not occur for python2. For tests I use debian 9 python `tango-9.2.5a` and the current develop branch of pytango (9.2.5). 

Does it mean that the `errors` attribute is dynamic and I have to check its existence. In the documentation it is written that is has always two levels.

**Comment by vxgmichel** [comment]
Hi @jkotan,

I don't think this code works with python 2 either. Accessing the `DevError` objects is done either using `exception[i]` in python 2 or `exception.args[i]` in python 2 and 3. The documentation does not make that clear though. 

Also, if you think errors should be accessed through an `errors` attribute (which would make sense), feel free to create a feature request.

**Comment by jkotan** [comment]
For `excepion[i]` I got the same errors. I have switched to `.errors` because I've seen  it at 

https://github.com/tango-controls/pytango/blob/8f022299bc6aa4d309317f9a8472a71c3e6fee0f/tango/utils.py#L1430

Is that also incorrect?

**Comment by jkotan** [comment]
But .. Thanks. I will try with args.

**Comment by vxgmichel** [comment]
> Is that is also incorrect?

Yea I think it is some c++ api legacy. Or maybe `.errors` used to be supported. I'm not entirely sure, this code is quite old. Good catch though.

**Comment by jkotan** [comment]
Indeed,  `args` works for me. But it would be good to mention it explicitly in the documentation
