### ISSUE TITLE
Unable to create Forwarded attributes in Python 9.2.4

### ISSUE THREAD

**Issue by jyotinpo** [tango-controls/pytango#231]
Hi @grm84,

I am exploring forwarded attributes feature in PyTango 9.2.4. 

As per [documentation](https://tango-controls.readthedocs.io/en/latest/development/device-api/forwarded-attribute.html), if `__root_attr` attribute property is not specified, the attribute is not created by the Tango kernel and is therefore not visible for the external world. The state of the device to which the forwarded attribute belongs to is set to ALARM (if not already FAULT) and a detailed error report is available in the device status. However, I get the following error when running the device server (with and without the `__root_attr` attribute property):

```python
Exiting: Server exited with tango.DevFailed:
DevFailed[
DevError[
    desc = ArgumentError: Python argument types in
               DeviceClass._create_fwd_attribute(ForwardedAttrTestPythonClass, AttrList, NoneType, UserDefaultFwdAttrProp)
           did not match C++ signature:
               _create_fwd_attribute(CppDeviceClass {lvalue}, std::vector<Tango::Attr*, std::allocator<Tango::Attr*> > {lvalue}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Tango::UserDefaultFwdAttrProp*)
           
  origin =   File "/usr/local/lib/python2.7/dist-packages/tango/device_class.py", line 341, in __DeviceClass__attribute_factory
    self._create_fwd_attribute(attr_list, attr_data.name, attr_data.att_prop)

  reason = PyDs_PythonError
severity = ERR]
]

Exited
```

Please note that I tried the same with Java and it works as expected. It seems that I am missing some configuration in the python code. Is there any documentation available for the same? Sample code is [ForwardedAttrTestPython.zip](https://github.com/tango-controls/pytango/files/2534489/ForwardedAttrTestPython.zip). Any inputs will be helpful.

Source: [Forum post](http://www.tango-controls.org/community/forum/c/development/python/forwarded-attributes-in-python/)

Regards,
@jyotinpo

**Comment by vxgmichel** [comment]
I also noticed that we don't have tests for forwarded attributes. This should be addressed too.

**Comment by grm84** [comment]
Hi @jyotinpo

Your server will run if you change the forward attribute definition to:
`    FwdAttr2 = attribute(name="FwdAttr2", label="FwdAttr2", forwarded=True)
`
The attribute name field is required.
Regards, Geoff.

**Comment by vxgmichel** [comment]
Thanks @grm84,

The related PR should include tests and some extra checks to raise more meaningful exceptions.

**Comment by jyotinpo** [comment]
Thanks, @grm84 and @vxgmichel ! 
Adding the attribute name field **resolved** the issue. This means that Pogo generator should be modified to generate the attribute name field automatically during code generation. Shall I raise a GitHub issue requesting this change?

**One observation:**
Let's say that during my device initialization, the root attribute device is not started due to which my forwarded device goes into ALARM state indicating the issue details. However, if the root device is started, the forwarded device doesn't absorb the changes but it requires a restart. I guess this is the normal behavior but do you think it will be good if it absorbs the changes dynamically? (Just a random thought though...)

Anyway, thank you very much for the prompt support on this issue.

Cheers!
