### ISSUE TITLE
Release 9.2.5

### ISSUE THREAD

**Issue by ajoubertza** [tango-controls/pytango#238]
I'm going to be releasing v9.2.5 after a request from @vxgmichel, for ESRF.  I'm doing it instead of him as a chance for me to learn.  It includes some fixes/improvements for gevent, Python 3, documentation, and DevEnum handling.

Task list:
- [x] Read steps in the how-to-contribute docs for making a release
- [x] Edit the changelog
- [x] Bump the version
- [x] Merge develop into stable
- [x] Make sure Travis is OK on stable branch
- [x] Make sure the documentation is updated (readthedocs)
- [x] Create a release tag on GitHub, from stable branch
- [x] Upload the new version to PyPI
- [x] Bump the version with "-dev" in the develop branch
- [x] Fill the release description on GitHub
- [x] Build conda packages
- [x] Advertise the release on the mailing list
- [x] Close this issue

**Comment by ajoubertza** [comment]
Uploaded new release to PyPI.
The readthedocs builds for develop (latest) and stable branches have been done, but the v9.2.5 tag doesn't show up yet, so those haven't been built.

**Comment by ajoubertza** [comment]
Can some from ESRF please build the Conda packages for this release?

**Comment by vxgmichel** [comment]
> Can some from ESRF please build the Conda packages for this release?

I'm on it!

**Comment by vxgmichel** [comment]
Done! https://anaconda.org/tango-controls/pytango/files?version=9.2.5

**Comment by ajoubertza** [comment]
Release is done.

**Comment by vxgmichel** [comment]
Great work, thanks a lot! :smiley:
