### ISSUE TITLE
Symbol % is not accepted in debug_stream logging

### ISSUE THREAD

**Issue by mrosanes** [tango-controls/pytango#243]
[ReportDS.txt](https://github.com/tango-controls/pytango/files/2634013/ReportDS.txt)

Symbol % is not accepted in PyTango self.debug_stream and self.error_stream for logging.
Currently we have designed a DS in order to logging errors with PyTango logger and be able to see the errors with the logviewer.
We have found out that % symbol is not accepted in the log messages, however in python is accepted. i.e:
In python we can print this without problems: print("It is 3%")
But the same message ("It is 3%") is not accepted by self.debug_stream and self.error_stream at it seems to wait for arguments.

Attached a DS with 3 commands. Two of them works correctly, and a third one using '%' without arguments in the message, presents the error described.

(I attached the DS with .txt format, it should be changed to .py)

**Comment by vxgmichel** [comment]
Those strings are formatted using the percent syntax, so you have to [escape the percent sign](https://stackoverflow.com/questions/10678229/how-can-i-selectively-escape-percent-in-python-strings):
```python
In [1]: "It is 3%%" % ()
Out[1]: 'It is 3%'

In [2]: "It is 3%" % ()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-1629bd5b9a52> in <module>()
----> 1 "It is 3%" % ()

ValueError: incomplete format
```
Alternatively you can use the python3 print function:
```python
print("It is 3%", file=self.log_error)
```

**Comment by mrosanes** [comment]
Thanks Vincent Michel, after replacing '%' by '%%' it works correctly.
