### ISSUE TITLE
Event tests fail on machines without a permanent IP address

### ISSUE THREAD

**Issue by tiagocoutinho** [tango-controls/pytango#246]
Some distributions like Debian create an extra entry in `/etc/hosts` on systems without a permanent IP address as a workaround for some software (e.g., GNOME). The `/etc/hosts` looks like this:
```
127.0.0.1 localhost
127.0.1.1 <host_name>

```
This is really improper because system hostnames and domain names are two very different things; but there you have it.

Currently, pytango tests retrieve this <host_name> and try to use it when building the GIOP (see [get_hostname()](../blob/develop/tango/test_context.py#L96)).

I propose to use directly the IP address instead.

**Comment by vxgmichel** [comment]
Hi @tiagocoutinho !

See #245 for a discussion about the failing tests.
