### ISSUE TITLE
Exception in init_device() blocks server

### ISSUE THREAD

**Issue by tiagocoutinho** [tango-controls/pytango#248]
If an exception is thrown in `init_device()` the server is blocked. 
A Ctrl-C to stop it generates a segmentation fault.

Used:
* python 2.7
* pytango 9.2.6
* tango C++ 9.2.5 & 9.3.2

**Comment by tiagocoutinho** [comment]
Seems to come from the C++ level.
I posted an issue [#506](https://github.com/tango-controls/cppTango/issues/506) there.

**Comment by tiagocoutinho** [comment]
Seems to come from libtango C++ on some linux versions.

I will close it here

**Comment by kklmn** [comment]
Is there any workaround in PyTango? I try to restart (run delete_device() and then init_device()) when a USB camera (cv2.VideoCapture()) hangs. But get the subj.
