### ISSUE TITLE
READ_WRITE attributes appear as WT_UNKNOWN in PyTango

### ISSUE THREAD

**Issue by sergirubio** [tango-controls/pytango#253]
When you look for TangoTest device on Jive; attributes appear as READ_WRITE

But, when asking the AttrWriteType from PyTango, they appear as WT_UNKNOWN

**Comment by sergirubio** [comment]
In [1]: import tango

In [2]: dp = tango.DeviceProxy('sys/tg_test/1')

In [3]: ac = dp.get_attribute_config('boolean_scalar')

In [4]: ac.writable
Out[4]: tango._tango.AttrWriteType.WT_UNKNOWN

In [5]:

**Comment by tiagocoutinho** [comment]
Hi @sergirubio,

is it fixed? can it be closed?

**Comment by ajoubertza** [comment]
Fixed in #254
