### ISSUE TITLE
Question about dynamic commands

### ISSUE THREAD

**Issue by dmiego** [tango-controls/pytango#256]
Hello.

I have a device with many modules in it and the command that reads data from them looks like:
`"r{}{}\r\n".format(str(module_number).zfill(2), var_name)`, where var_name can be ISet, VSet, IMon or VMon.

I don't know which modules will be used next time, so I try to make the DS flexible and do module scanning in init_device() method and get list of present modules.

So my question is:
can I dynamically create commands in the DS with names like "ISet_01_read", 'VSet_01_read", etc. which will send command to read defined parameter from the module with defined ID?

As far as I understand - DS command name is the `__name__` var of method that passed in argument "f" for command constructor. But I can't pass any arguments to this method and reuse it for another command because of the same `__name__`

**Comment by dmiego** [comment]
Also I can't enable polling for dynamically created command, even without requirements, listed in previous comment.

```
def init_device(self):
    Device.init_device(self)
    self.add_dyn_cmd()

......

def start(self):
    print('start')

def add_dyn_cmd(self):
    device_level = True
    cmd = command(f=self.start, polling_period=5000)
    self.add_command(cmd, device_level)
```

![image](https://user-images.githubusercontent.com/13482645/52637630-d0ac1000-2ee0-11e9-8617-81457da89375.png)

**Comment by ajoubertza** [comment]
Hi @Diego91RA 

That's an interesting problem.  I'm not sure if you can do it with PyTango directly, but you can do it by using some Python tricks to dynamically create the class at runtime.  We do this in [tango-simlib](https://github.com/ska-sa/tango-simlib) which creates a device server using the attributes and commands defined in a config file.  For each command and attribute "actions" can be defined.

There's a lot of code to wade through, but this method seems to be at the heart of it:  https://github.com/ska-sa/tango-simlib/blob/aaa3fa02c9/tango_simlib/utilities/helper_module.py#L127  - it is basically overwriting the `__name__` attribute.  Maybe that is sufficient?

Here's an example of a DS created in this way:  https://github.com/ska-sa/tango-simlib/blob/31e7188/tango_simlib/examples/weather1.py

Here's the method that creates the device server class:  https://github.com/ska-sa/tango-simlib/blob/effb68c/tango_simlib/tango_sim_generator.py#L81,
and in particular, this one adds commands dynamically:  https://github.com/ska-sa/tango-simlib/blob/effb68c/tango_simlib/tango_sim_generator.py#L318

Maybe that can give you some clues.

As for question 2, I'm not 100% sure, but trying to add a command or attribute during `init_device` seems problematic.  The device is trying to start up, so it (and its admin device, or "dserver") isn't necessarily functioning properly yet.  Creating the class dynamically, before starting may solve that problem too.

**Comment by dmiego** [comment]
Hi @ajoubertza.
Thanks for examples, it helped me figuring out how it works. So I tried to edit PyTango code and here are the changes that I made. (actually I've edited source in `site-packages` folder, but it doesn't matter)
https://github.com/Diego91RA/pytango/commit/6daa18af9ef262a5d6fb74db862159d8c92814f0
I don't know if it fits Tango style or safety rules, but it works :)

And here is the example of usage:

```
def add_read_function(self, mod_id):
    fn_name = 'read_{}'.format(str(mod_id).zfill(2))
    def fn():
        print(fn_name, mod_id)
    setattr(self, fn_name, fn)

def add_dyn_cmd(self):
    for mod in self.modules:
        self.add_read_function(mod[0])
        func = getattr(self, 'read_{}'.format(str(mod[0]).zfill(2)))
        cmd = command(f=func,
                  display_level=DispLevel.EXPERT, cmd_name='read_{}'.format(str(mod[0]).zfill(2)))
        self.add_command(cmd, True)
```
So now I have many commands with different names, but with the same template.

But still I can not poll them. I even tried to add commands the same way as it made for attrs in the  [dyn_attr](https://github.com/tango-controls/pytango/blob/86cc662bd2f1d3ee49af93ade067aa3195ddd479/tango/server.py#L424) method, but it didn't help anyway.

**Comment by bourtemb** [comment]
Thanks for the bug report @Diego91RA .
I created https://github.com/tango-controls/cppTango/issues/538 to keep track of this bug.
In the mean time, you could try adding the command with device_level set to False:
```
def add_dyn_cmd(self):
    device_level = False
    cmd = command(f=self.start, polling_period=5000)
    self.add_command(cmd, device_level)
```
Of course this will not help you if you have instances of your device server exporting several devices and if you require different dynamic commands for the different devices from the same device server instance.

**Comment by tiagocoutinho** [comment]
Seems to come from C++. Is it ok to close it here?

**Comment by dmiego** [comment]
Hi Tiago.
Polling works fine with "False" for `device_level`, so my problem solved.
I think the issue can be closed.
