### ISSUE TITLE
TRANSIENT_CallTimedout and unidentifiable C++ exception with multiprocessing

### ISSUE THREAD

**Issue by jkotan** [tango-controls/pytango#259]
Hi, 

I would like to ask if PyTango pretends to work with `Process`'es from multiprocessing?

If I write a simple stress test with `Process` 
```python
import time
import PyTango

from multiprocessing import Process


class Worker(Process):

    def __init__(self):
        Process.__init__(self)

    def run(self):
        proxy = PyTango.DeviceProxy('test/tserver/1')

        stime = time.time()
        etime = stime
        while etime - stime < 1.:
            try:
                proxy.read_attribute("Value")
            except Exception as e:
                print(str(e))
            etime = time.time()


def runworkers():
    workers = [Worker() for _ in range(6)]
    for wk in workers:
        wk.start()
    for wk in workers:
        wk.join()


db = PyTango.Database()
dp = PyTango.DeviceProxy('test/tserver/1')

for i in range(4):
    runworkers()
```
with the following test server:
```python
from PyTango.server import run, Device, DeviceMeta, attribute
from PyTango import AttrWriteType


__all__ = ["TServer", "main"]


class TServer(Device):

    __metaclass__ = DeviceMeta

    Value = attribute(
        dtype='double',
        access=AttrWriteType.READ,
        doc="scalar attribute",
    )

    def read_Value(self):
        return 0.0


def main(args=None, **kwargs):
    return run((TServer,), args=args, **kwargs)


if __name__ == '__main__':
    main()
```
I get a lot of errors of type:
```bash
DevError[
    desc = Failed to read_attribute on device test/tserver/1, attribute Value
  origin = DeviceProxy::read_attribute()
  reason = API_AttributeFailed
severity = ERR]
]
DevFailed[
DevError[
    desc = TRANSIENT CORBA system exception: TRANSIENT_CallTimedout
  origin = DeviceProxy:read_attribute
  reason = API_CorbaException
severity = ERR]

DevError[
    desc = Timeout (3000 mS) exceeded on device test/tserver/1
  origin = DeviceProxy:read_attribute
  reason = API_DeviceTimedOut
severity = ERR]
]
DevFailed[
DevError[
    desc = TRANSIENT CORBA system exception: TRANSIENT_CallTimedout
  origin = DeviceProxy:read_attribute
  reason = API_CorbaException
severity = ERR]

DevError[
    desc = Timeout (3000 mS) exceeded on device test/tserver/1
  origin = DeviceProxy:read_attribute
  reason = API_DeviceTimedOut
severity = ERR]
]
```
Moreover if I comment 
```python
dp = PyTango.DeviceProxy('test/tserver/1')
```
in the above test script I get other random errors 
```bash
Process Worker-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "./runner.py", line 13, in run
    proxy = PyTango.DeviceProxy('test/tserver/1')
  File "/usr/lib/python2.7/dist-packages/tango/device_proxy.py", line 171, in __DeviceProxy__init__
    return DeviceProxy.__init_orig__(self, *args, **kwargs)
RuntimeError: unidentifiable C++ exception
Process Worker-17:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "./runner.py", line 13, in run
    proxy = PyTango.DeviceProxy('test/tserver/1')
  File "/usr/lib/python2.7/dist-packages/tango/device_proxy.py", line 171, in __DeviceProxy__init__
    return DeviceProxy.__init_orig__(self, *args, **kwargs)
RuntimeError: unidentifiable C++ exception
```
Futhermore, if I comment both
```python
db = PyTango.Database()
dp = PyTango.DeviceProxy('test/tserver/1')
```
the script runs without any error.
I've performed my tests in debian 10: `python-pytango 9.2.5-1` and `tango-* (9.2.5a)`.

It also happened for tests with servers written in Cpp or Java so it looks like it is a client problem.

Does it mean if I use `Process`'es I'm not allowed to create `DeviceProxy/Database` objects in the main script (so all  my tasks with `DeviceProxy` I have to delegate to my `Process`es) or it is just a bug?

Bests,
Jan

**Comment by andygotz** [comment]
Hi Jan,

this sounds like a very interesting use case viz. multiprocessing with PyTango.  It seems like there is some shared state with the main thread if you create the DeviceProxy in the main thread. But I couldn't say if this is in the Python or C++ part. We will have to get an expert to confirm this.

The good news is that the script runs when you delegate the DeviceProxy to the worker processes. Is it a problem for your use case to delegate the proxy to the worker process?

Cheers
Andy

**Comment by jkotan** [comment]
Hi Andy,

Yes, when I put all my `DeviceProxy/Database` objects to separate `Process`'es I do not get any error.

Cheers,
Jan

**Comment by jkotan** [comment]
Indeed, it comes from c++.

**Comment by tiagocoutinho** [comment]
@jkotan,
The python *multiprocessing.Process* does a simple `fork()` behind the scenes.
This means your child process will inherit the context from your parent process.
And this includes open file descriptors, the TANGO and the CORBA state.

I don't think TANGO/CORBA are prepared to handle forking (maybe the libtango C++ experts can expand on this)

Therefore, be careful when using *multiprocessing* with *PyTango*. To be safe, you **must** ensure that on the parent process the CORBA initiation is not triggered. This basically means not creating any instance of Tango objects (Database, DeviceProxy, AttributeProxy, ...)

I think you already figured out this by yourself. I only wanted to give the explanation why.

**Comment by ajoubertza** [comment]
I'm closing this issue - it has been explained and nothing to be done in PyTango.

**Comment by jkotan** [comment]
Hi @ajoubertza, in order to cure the problem one can add `ApiUtil.cleanup()`, see #260.
