### ISSUE TITLE
python 3, pytango 9.3  : client.Object, UnicodeDecodeError

### ISSUE THREAD

**Issue by dnaudet** [tango-controls/pytango#268]
Hi PyTango,

we've run into some problem when using PyTango's client.Object and Server with python 3 (pytango 9.3 installed from the tango conda repo).

For instance, when I try the dynamic_server and dynamic_client examples (found on this git), attributes work fine, but as soon as I try to call a function, here's what I get:
- it works fine when both client and server are running with python 2
- there is some pickle incompatibilities if the client and server are not running the same version of python (tried 2.7 and 3.7)
- there is some UnicodeDecodeError ('utf-8' codec can't decode byte 0x80 in position 0: invalid start byte') if both client/server are in python 3.

So, as I couldn't seem to find any documentation on those classes, I was wondering if I am doing something wrong, or maybe it's not supported anymore?

Thanks!
Cheers,
Dam

**Comment by tiagocoutinho** [comment]
Hi @dnaudet,
This looks like a side effect of a critical bug fix on the latest PyTango 9.3.
Thanks for the report. I will check ASAP.

**Comment by dnaudet** [comment]
thanks @tiagocoutinho! BTW, I think the problem was already there a few months ago, so it's not just a regression from 9.3, if that's what you meant.
Cheers.

**Comment by laurent-claustre** [comment]
Hi with the latest package in preparation, could we have this issue fixed as well?
Thanks for your help.
