### ISSUE TITLE
pytango-9.3.0 / python 2.7: six.ensure_binary non available with six 1.11.0

### ISSUE THREAD

**Issue by claudio-scafuri** [tango-controls/pytango#272]

**Comment by claudio-scafuri** [comment]
on ubuntu 18.04 with six 1.11.0 method six.ensure_binary() is not available.
(availablerom 1.12.0 and later?)

**Comment by claudio-scafuri** [comment]
correcet : pytango-9.3.0 !!

**Comment by ajoubertza** [comment]
@claudio-scafuri Thanks for the report.  You are correct.  This was raised in issue #269 and fixed in PR #270.  You will have to install a newer version of six.
