### ISSUE TITLE
Get device status

### ISSUE THREAD

**Issue by nfalcoz** [tango-controls/pytango#279]
Dear All, 
we use the method described in : https://tango-controls.readthedocs.io/en/latest/tutorials-and-howtos/how-tos/how-to-pytango.html to check the status of our device servers. 
For that we used the following  code : 
```python
   def get_device_info(self, dev):
        vals = PyTango.DeviceProxy('sys/database/2').DbGetDeviceInfo(dev)
        di = dict((k,v) for k,v in zip(('name','ior','level','server','host','started','stopped'),vals[1]))
        di['exported'],di['PID'] = vals[0]
        return di
```
for some devices we got the message : 
```
{'PID': 14276,
 'exported': 1,
 'host': 'cpci-b15',
 'ior': 'IOR:010000001700000049444c3a54616e676f2f4465766963655f343a312e300000010000000000000068000000010102000f0000003139322e3136382e3232392e3636000084c800000e000000fee3aa945c000037c4000000000100000200000000000000080000000100000000545441010000001c00000001000000010001000100000001000105090101000100000009010100',
 'level': '4',
 'name': 'dserver/genericpowersupply/alim-dpiel',
 'server': 'GenericPowerSupply/alim-DpiEL',
 'started': '22nd March 2019 at 10:27:45',
 'stopped': '20th March 2019 at 16:09:35'}
```
but the device is stopped. 
does it mean the device is badly stopped ? 

and also for some cases : 
```
{'PID': 6336,
 'exported': 1,
 'host': 'cpci-b15',
 'ior': 'IOR:010000001700000049444c3a54616e676f2f4465766963655f343a312e300000010000000000000068000000010102000f0000003139322e3136382e3232392e3636000094c100000e000000feef54925c000018c0000000000100000200000000000000080000000100000000545441010000001c00000001000000010001000100000001000105090101000100000009010100',
 'level': '4',
 'name': 'dserver/genericpowersupply/alim-colli1',
 'server': 'GenericPowerSupply/alim-ColLI1',
 'started': '20th March 2019 at 15:56:33',
 'stopped': '?'}
```
what does mean the '?'   ??

Is there another method to check if a DS is started or not. 

Thx for the feedback

**Comment by bourtemb** [comment]
> for some devices we got the message :
> 
> ```
> {'PID': 14276,
>  'exported': 1,
>  'host': 'cpci-b15',
>  'ior': 'IOR:010000001700000049444c3a54616e676f2f4465766963655f343a312e300000010000000000000068000000010102000f0000003139322e3136382e3232392e3636000084c800000e000000fee3aa945c000037c4000000000100000200000000000000080000000100000000545441010000001c00000001000000010001000100000001000105090101000100000009010100',
>  'level': '4',
>  'name': 'dserver/genericpowersupply/alim-dpiel',
>  'server': 'GenericPowerSupply/alim-DpiEL',
>  'started': '22nd March 2019 at 10:27:45',
>  'stopped': '20th March 2019 at 16:09:35'}
> ```
> 
> but the device is stopped.
> does it mean the device is badly stopped ?

Yes. It looks like the device server didn't get the time to unregister before stopping.

> 
> and also for some cases :
> 
> ```
> {'PID': 6336,
>  'exported': 1,
>  'host': 'cpci-b15',
>  'ior': 'IOR:010000001700000049444c3a54616e676f2f4465766963655f343a312e300000010000000000000068000000010102000f0000003139322e3136382e3232392e3636000094c100000e000000feef54925c000018c0000000000100000200000000000000080000000100000000545441010000001c00000001000000010001000100000001000105090101000100000009010100',
>  'level': '4',
>  'name': 'dserver/genericpowersupply/alim-colli1',
>  'server': 'GenericPowerSupply/alim-ColLI1',
>  'started': '20th March 2019 at 15:56:33',
>  'stopped': '?'}
> ```
> 
> what does mean the '?' ??

I guess it means that the device server has never been stopped until now. So it is running and it is the first time it is running.

> Is there another method to check if a DS is started or not.

You can try to execute the ping command on its admin device?

**Comment by ajoubertza** [comment]
@nfalcoz There are also some useful tools for querying and modifying a TANGO system programmatically provided by the fandango project ([readthedocs](https://tango-controls.readthedocs.io/en/latest/tutorials-and-howtos/how-tos/how-to-fandango.html), [github](https://github.com/tango-controls/fandango)).

**Comment by hayg25** [comment]
Dear @bourtemb, 
so for you, the "standard" method to access the list of running devices is the one described in this issue or you would recommend another method? 
For example, one could try loop over the DS using a try/except but this takes time ... 
Concerning the ping command, you mean using tango_admin ? 
I tried for example tango_admin :  
```
--ping-device <dev> [max_time (s)] Check if the device is running
```
for example I tried : 
```
/usr/lib/tango/tango_admin --ping-device sys/tg_test/1  5
``` 
no output ... 

thanks for the feedback

**Comment by ajoubertza** [comment]
Hi @hayg25 

I'm not sure if there is a "standard" way to do this, but here are some more options:
- A scriptable option is via Fandango's Astor-like controls:  https://tango-controls.readthedocs.io/en/latest/tutorials-and-howtos/how-tos/how-to-fandango.html#start-stop-all-device-servers-in-a-machine-like-astor-stop-all
- If you prefer a graphical tool, see Astor ([github](https://github.com/tango-controls/astor), [docs](http://www.esrf.eu/computing/cs/tango/tango_doc/tools_doc/astor_doc/index.html)).

Note that the `tango_admin` doesn't print much - you need to check the exit code.  `0` means it worked, anything else indicates failure.  E.g.
```
$ /usr/lib/tango/tango_admin --ping-device sys/tg_test/1  5
$ echo $?
255
```
(Source is [here](https://github.com/tango-controls/tango_admin)).
Another example of using the `tango_admin` device is in the `Starter` [script](https://tango-controls.readthedocs.io/en/latest/tutorials-and-howtos/how-tos/how-to-try-tango/tango-starter-daemon.html).
