### ISSUE TITLE
New HotFix release of PyTango for Sardana 2.7.1, 2.7.2 and 2.8.0

### ISSUE THREAD

**Issue by aureocarneiro** [tango-controls/pytango#284]
Hey,

The new Sardana versions (2.7.1, 2.7.2 and 2.8.0) are not compatible with the latest PyTango (9.3.0).
This is the issue. #271 
This is the PR already merged on develop branch #273

So I want a small hotfix release for we can follow the upstream versions at MAX IV.

Thank you,

/Aureo

**Comment by ajoubertza** [comment]
@aureocarneiro In case you didn't see the other new issues, the new release is in progress: #287
