### ISSUE TITLE
Prepare 9.3.1

### ISSUE THREAD

**Issue by tiagocoutinho** [tango-controls/pytango#287]
This is to inform the community that 9.3.1 is being prepared

- [x] Read steps in the how-to-contribute docs for making a release
- [x] Pull request to update changelog and bump version
- [ ] Update `.travis.yml` with a conda package using a final cppTango 9.3.x release?
- [x] Merge PR (this is the last PR for the release)
- [x] Merge develop into stable
- [x] Make sure Travis and Appveyor are OK on stable branch
- [x] Make sure the documentation is updated for stable (readthedocs)
- [x] Create a release tag on GitHub, from stable branch
- [x] Make sure the documentation is updated for release (readthedocs)
- [x] Upload the new version to PyPI
- [x] Bump the version with "-dev" in the develop branch
- [x] Fill the release description on GitHub
- [x] Build conda packages
- [x] Advertise the release on the mailing list
- [x] Close this issue

**Comment by tiagocoutinho** [comment]
Hi @tango-controls/pytango-developers,

I was thinking it would be nice to have a 9.3.1.

For ALBA, it would be important to include #285 and #286.

Does anyone have something more they would like to see in the release?
Thanks in advance for the help

**Comment by ajoubertza** [comment]
@tiagocoutinho A new release sounds good.  That would also help with the request in #287.

I would have liked #281 to be included, but not sure if @sdebionne has made any progress on it?  If not, does it look like something you could fix, @tiagocoutinho?

I will also make a documentation update following #282.

**Comment by tiagocoutinho** [comment]
> @tiagocoutinho A new release sounds good. That would also help with the request in #287.

Cool!

> I would have liked #281 to be included, but not sure if @sdebionne has made any progress on it? If not, does it look like something you could fix, @tiagocoutinho?

Sure, I can have a look at it. I synchronize with @sdebionne to make sure we are not duplicating work.

**Comment by sdebionne** [comment]
I did have a quick look at #281 but could not find anything obvious. I'll try got give it another go next Friday. My guess was that a converter from `PyByteArray` to `char *` was missing but that did not fix the issue.

**Comment by ajoubertza** [comment]
@tiagocoutinho Can we get a conda build of cppTango 9.3.3 and use that for tests?

**Comment by ajoubertza** [comment]
@tiagocoutinho Are you busy preparing a branch for this version, or should I?

**Comment by tiagocoutinho** [comment]
@ajoubertza, I can take care of the conda package for cppTango. 

It would be great if you could prepare the branch for pytango 9.3.1.

I am also trying to prepare git repos for conda recipes for both cppTango and pyTango.
I have a question (actually a generic question for the tango community):
I would like to put them in gitlab to take advantage of gitlab CI. Is it ok with you or you prefer to put them in github.com/tango-controls?

**Comment by ajoubertza** [comment]
> It would be great if you could prepare the branch for pytango 9.3.1.

OK, will do.

> I have a question (actually a generic question for the tango community):
> I would like to put them in gitlab to take advantage of gitlab CI. Is it ok with you or you prefer to put them in github.com/tango-controls?

I like the code to live in Github, since all the users work on it already have access, and know the system.  Also nice to have a single place to look for tango-related code.   That being said, Gitlab's CI is nice too.  SKA are using both.  The development and "source of truth" is on Github, but they [mirror](https://docs.gitlab.com/ee/workflow/repository_mirroring.html) the repos onto Gitlab for CI.  I propose this.  Would like to hear other opinions.

I see there is already a [tango-controls](https://gitlab.com/tango-controls) group on Gitlab.  It is empty at the moment.  Only member is @gjover - hopefully he can give you access, if we go this way.  And then it could become an "official" group.

**Comment by tiagocoutinho** [comment]
> The development and "source of truth" is on Github, but they mirror the repos onto Gitlab for CI. I propose this. Would like to hear other opinions.

Sounds good to me

> I see there is already a tango-controls group on Gitlab. It is empty at the moment. Only member is @gjover - hopefully he can give you access, if we go this way. And then it could become an "official" group.

There should be no problem. @gjover works 10 meters away from me :-)

**Comment by ajoubertza** [comment]
@tiagocoutinho Are you close to having a cppTango 9.3.3 conda package ready?  I'd like to update the Travis tests to use it.  Similarly, what is happening with the PyTango conda recipe?

Do we need to wait for these before the release, or can I do it today?

**Comment by ajoubertza** [comment]
@tiagocoutinho Any feedback on my questions from last week (see above)?  If not, I'm going to proceed with this release tomorrow.

**Comment by ajoubertza** [comment]
I've tried building the release, but the [AppVeyor artefacts](https://ci.appveyor.com/project/ajoubertza/pytango/builds/26544542/job/62hoomw1js37sjfe/artifacts) come out as `9.3.1dev1` instead of `9.3.1`.  I thought I could just rename the wheel files, but their contents also have this incorrect version info.

This build is with the `v9.3.1` annotate tag present.  The log shows the expected version info:
```
[00:00:35] -- GIT_VERSION: 9.3.1
[00:00:35] -- PROJECT_VERSION: 9.3.1
[00:00:35] -- PACKAGE_VERSION: 9.3.1
```
Any ideas @tiagocoutinho @sdebionne @NexeyaSGara?

**Comment by ajoubertza** [comment]
Never mind - I made a mistake - forgot to update [tango/release.py](https://github.com/tango-controls/pytango/blob/5ee7748d881827badcd13748bc57f5bd6046d8a2/tango/release.py#L48) file!  (Even the sdist build had the `9.3.1dev1` version)
I'm going to update and move the tag.

**Comment by ajoubertza** [comment]
@andygotz I've uploaded the v9.3.1 PyTango release to PyPI. Can you please request someone at ESRF to build the Conda package?

**Comment by tiagocoutinho** [comment]
Hi @ajoubertza,
Sorry for coming in so late.

I have started projects to build conda packages for Tango C++ on linux, PyTango on linux and PyTango on windows:

* https://gitlab.com/tiagocoutinho/tango-conda-recipes
* https://gitlab.com/tiagocoutinho/pytango-conda-recipes
* https://gitlab.com/tiagocoutinho/pytango-windows-conda-recipes

They are just staging areas. We are of course free to restructure and/or move them as we please.

They are not working yet. I hope to have some time next week to make all of this work.
Any feedback is very welcome.

**Comment by ajoubertza** [comment]
Hi @tiagocoutinho 
I was wondering what happened.  Can you arrange with @andygotz that the ESRF pipeline is used to build the Linux conda package in the meantime?  I'd like to announce this release, but we're supposed to wait until the conda package is available.

**Comment by tiagocoutinho** [comment]
@ajoubertza, I have uploaded the conda packages for python 2.7, 3.6 and 3.7

The linux repository I mentioned above is configured with gitlab CI to build conda packages. 

The windows repository contains the script to build the conda package + documentation on how to do it. There is no CI for it.

Let me know if there is something missing

**Comment by ajoubertza** [comment]
Thanks for conda packages @tiagocoutinho. 

For the Windows conda packages, the [previous discussion](https://github.com/tango-controls/pytango/issues/276#issuecomment-494263998) about this suggested we use feature like "python-static".  Did that happen yet?

**Comment by ajoubertza** [comment]
> Let me know if there is something missing

Sorry, I don't know enough about conda to see if something is missing.  Seems like the recipes are working.   Would like them to move to https://gitlab.com/tango-controls (or maybe they should just be added to this repo?).
