### ISSUE TITLE
Object memory leak when calling repr(DeviceProxy)

### ISSUE THREAD

**Issue by birkenfeld** [tango-controls/pytango#298]
Calling `repr(device_proxy)` creates a reference cycle that apparently involves non-GC aware objects that should be GC aware.

Reproduce with:
```
import gc, tango

while True:
    gc.collect()
    print(len(gc.get_objects()))
    proxy = tango.DeviceProxy('sys/tg_test/1')
    repr(proxy)
```

When you comment out the `repr(proxy)` line, the printed object count stays constant as it should. With the `repr` call, objects are leaked on every loop iteration.

The problem is caused by the result of `dev.info()` being assigned to `dev._dev_info`, and a reference cycle is created. This is normally handled by the GC, but only if every object in the reference cycle is GC aware.

**Comment by ajoubertza** [comment]
@birkenfeld Interesting problem.  I wonder if the solution to both issues is the same.

**Comment by vallsv** [comment]
Hi, we have the exact same problem with `str(proxy)`. Would be nice reach inside the problem.

`__str__`, and `__repr__` are basically used everywhere when you debug suffs. Used by ipython output, loggers... It makes the problem really really difficult to solve.
