### ISSUE TITLE
Support pogo's *mandatory property* feature in PyTango and PyTango pogo plugin

### ISSUE THREAD

**Issue by tiagocoutinho** [tango-controls/pytango#30]
Pogo has a new feature for each property called _mandatory_ property.
If set, it generates code that puts the device is some state if the property is not set in the database.

PyTango and the pogo plugin for PyTango don't support this feature yet. It would be nice to have it.

Thanks to Jens Meyer for reporting this.

**Comment by tiagocoutinho** [comment]
I propose to had a new keyword argument to `device_property(mandatory=False)` that will trigger the same behavior in PyTango.

For old style PyTango servers, I propose:
`device_property_list = { '<prop_name>': [<type>, <desc>, <default>[, <mandatory>]]`

Pogo plugins for PyTango (both old and new) need to be modified to support this as well

**Comment by NexeyaSGara** [comment]
I can add this to the templates, once we are sure of the syntaxe.

**Comment by NexeyaSGara** [comment]
Since there is no comment on the syntaxe, I will use what you proposed

**Comment by tiagocoutinho** [comment]
I am not sure I understand what you mean. My apologies because I mixed BNF with python syntax in the example for old style PyTango servers. Here is a more clear explanation:
```
# last field represents mandatory. If omitted is False by default
device_property_list = { <prop_name>: [<type>, <desc>, <default>, <mandatory>] } 
``` 
Is this what you had in mind?

**Comment by NexeyaSGara** [comment]
Exactly :)

I will imlement it for the next Pogo version

**Comment by NexeyaSGara** [comment]
Here is an example :

'Test':
            [PyTango.DevString, 
            "Desc Test",
            mandatory=True,
            [] ],

**Comment by vxgmichel** [comment]
Done, thanks everyone!
