### ISSUE TITLE
Configure timeout

### ISSUE THREAD

**Issue by stanislaw55** [tango-controls/pytango#304]
Hello PyTango developers,
I have following question: in one of my devices, connection takes significant amount of time, more than 3000 ms. It is one single operation so it cannot be split into multiple actions. 

When I try to execute command, there's timeout error from Tango site. How can I solve my problem? Should I use green mode? Or is there any way to make timeout threshold higher for this one command?

**Comment by piogor** [comment]
Hi @stanislaw55, it would be probably good to post this kind of question on [Forum](https://www.tango-controls.org/community/forum/c/development/python/), too.

Have you tried:
- to use `wait` and `timeout` arguments of [command_inout](https://pytango.readthedocs.io/en/stable/client_api/device_proxy.html#tango.DeviceProxy.command_inout)?
- or call [set_timeout_millis(self, timeout)](https://pytango.readthedocs.io/en/stable/client_api/device_proxy.html#tango.DeviceProxy.set_timeout_millis) before and after your command call?

Anyway, the solution I would suggest is to implement a `connect` command on a device server side with the following pattern:
- change the device state to indicate the connection is in progress,
- start a background thread for establishing the connection,
- and return immediately.
The thread, when the connection is established, set device state to indicate success.
On the client side it is now possible just to wait for the right state.

**Comment by stanislaw55** [comment]
Hi @piogor 
Thanks for rapid reply!
Solution you proposed seems right. But I have a question about threads: is `tango.server.Device` thread-safe?

**Comment by piogor** [comment]
For this, I am not an expert.  However, I used to use threads created within a python device, just remembering to have a mutex around data modification calls (like set_state() ), and it works.

**Comment by stanislaw55** [comment]
So I will try with threads.
Thanks!

**Comment by jkotan** [comment]
Hi,
In my opinion it is better not to cali `set_state()` from your user thread. The mutex may not help in this case  because it's internal calls are not protected.

**Comment by stanislaw55** [comment]
Hi @jkotan 
Thank you for your answer. Do you know any method do configure Tango timeout on command?

**Comment by jkotan** [comment]
I think Piotr has already answered for this question, i.e. set_timeout_millis(self, timeout) or wait and timeout arguments of command_inout or threads.
