### ISSUE TITLE
Read value for attribute XXX has not been updated

### ISSUE THREAD

**Issue by stanislaw55** [tango-controls/pytango#305]
Hello PyTango community
I am using dynamic attributes in my DS and everything works fine when launching DS instance. However, when I try to read one of my dynamic attributes, following error appears.

`Read value for attribute XXX has not been updated`

I've used examples from documentation to create DS. Have someone the same issue?
PyTango: 9.2.2
Tango: 9.2.5

**Comment by tiagocoutinho** [comment]
@stanislaw55, could you post the code you did? It would give a better clue on where the problem might be.

Thanks in advance

**Comment by stanislaw55** [comment]
Hi @tiagocoutinho 
Of course, please see code below

```python
from tango import DevDouble, AttrWriteType, Attr, DevState
from tango.server import Device, DeviceMeta, device_property


class DynamicAttrTest(Device):

    __metaclass__ = DeviceMeta

    Axes = device_property(
        (str,),
        doc="List of axes"
    )

    def init_device(self):
        """
        Device Server initialization
        :return: None
        """
        super(DynamicAttrTest, self).init_device()
        self.set_state(DevState.INIT)
        self.set_status("Device is initializing")

        self._positions = {}

        for axis in self.Axes:
            pos_attr = Attr("Position_%s" % axis, DevDouble, AttrWriteType.READ_WRITE)
            self.add_attribute(pos_attr, self.read_position, self.write_position, self.is_position_allowed)
            self._positions["Position_%s" % axis] = 0.0

        self.set_state(DevState.ON)
        self.set_status("Device is running")

    def read_position(self, attr):
        self.debug_stream("Reading attribute %s" % attr.get_name())
        return self._positions[attr.get_name()]

    def write_position(self, attr, value):
        self.debug_stream("Writing attribute %s" % attr.get_name())
        print("Doing some stuff")

    def is_position_allowed(self, attr):
        return self.get_state() != DevState.FAULT
```

It is stripped down, minimal example of what I've coded.
Sorry for not attaching code previously.

**Comment by tiagocoutinho** [comment]
I confirm the bug @stanislaw55.

In the old versions of PyTango the way to code a read attribute method was something like this:
```python
def read_position(self, attr):
    ...
    attr.set_value(calculated_position)
```

This was not very pythonic so a new interface was designed (the one you use) that looks more to what a python programmer would expect:
```python
def read_position(self):
    ...
    return calculated_position
```

It seems the dynamic attributes have **not** been ported to the new interface. This is missing even in PyTango 9.3.1 and needs to be done.

As a workaround you can do:
```python
def read_position(self, attr):
    self.debug_stream("Reading attribute %s" % attr.get_name())
    attr.set_value(self._positions[attr.get_name())
```

Thanks for reporting the bug.

**Comment by stanislaw55** [comment]
Thank you @tiagocoutinho!
Your workaround works just fine.
