### ISSUE TITLE
Change TANGO_HOST in process

### ISSUE THREAD

**Issue by woutdenolf** [tango-controls/pytango#308]
I need to get device proxies from different databases on different host without using the full device uri (I'm not actually creating the proxies myself, so I do not have control over the uri):
```python
import os
from tango import DeviceProxy
os.environ['TANGO_HOST'] = 'host1:10000'
prx = DeviceProxy('a1/b1/c1')
os.environ['TANGO_HOST'] = 'host2:10000'
prx = DeviceProxy('a2/b2/c2')  # FAILS: is still using 'host1:10000'
```
So the default TANGO_HOST is cached somehow. Can I clear this cache or set the default TANGO_HOST explicitely?

**Comment by ajoubertza** [comment]
Hi @woutdenolf.

I'm not sure if it is possible.  I think the DB connection details may be stored in the `ApiUtil` singleton.  In v9.3.0 we added a method `ApiUtil.cleanup()` to deal with problems using `DeviceProxy` instances with multiprocessing.  See [issue](https://github.com/tango-controls/pytango/issues/259), and [doc](https://pytango.readthedocs.io/en/stable/howto.html#using-clients-with-multiprocessing).  PyTango is just calling a method in libcppTango, and the docstring says this:
https://github.com/tango-controls/pytango/blob/492c8752650744b88112bebc450f8497a8b0315b/tango/api_util.py#L136-L143

I thought you could use this method before changing the `TANGO_HOST` variable.  It does allow me to create the new `DeviceProxy` instance with the new details, but it also breaks the `DeviceProxy` linked to the previous host.

> (I'm not actually creating the proxies myself, so I do not have control over the uri)

I'm not quite sure why you cannot change the URIs that `DeviceProxy` instances are using, but if you could get the creation of the instances that are using different TANGO facilities (i.e., using different databases) to be spawned in different processes you could work around it that way.

**Comment by tiagocoutinho** [comment]
I agree with @ajoubertza.

When you import PyTango on a python process, it loads the underlying Tango C++ library. This library reads the  environment variable in an independent way from python so as far as I know there is no way from within python to affect that value.

My suggestion is that you supply your users with a method that is able to handle the tango URL as you see fit (see example below)

```python
from urllib.parse import urlparse
from tango import DeviceProxy

def Device(name):
    url = urlparse(name)
    url.netloc = 'host1:10000'
    return DeviceProxy(url.geturl())
```

**Comment by woutdenolf** [comment]
```ApiUtil.cleanup()``` does what I want. The use case is unit testing: I need a clean environment for each test (with a new tango db at random port) so I do not need to preserve existing proxies. Using the full tango url as you suggested is better of course, but I do not launch the device server myself or specify its url (this is all done in a subprocess launched by the Bliss library which my tests run against). Anyway, calling the cleanup routine works and makes sense in this use case. Thanks!
