### ISSUE TITLE
Unable to compile PyTango with boost 1.69 on CentOS 7.7

### ISSUE THREAD

**Issue by stanislaw55** [tango-controls/pytango#310]
Hello PyTango community,
recently I've been trying to compile PyTango on CentOS 7.7 with boost version 1.69 using Python 3.6. In CentOS, it is accessible under `boost169`, not `boost` in `/usr/lib64` or `/usr/include`. I had to make symbolic link in order to make it work.

Apart from that, there was wrong assumption of boost python library name. It looks for `libboost_python3`, but there's `libboost_python36`.

AFAIK, all logic responsible for discovering platform, libraries and similar stuff is present in `setup.py`, right? In case of any change or adaptation, it requires manual maintainer intervention.
AFAIK compilation on Windows utilises CMake to handle all those paths and cases. What about using CMake to compile PyTango on both Linux and Windows? I haven't tested it but maybe CMake could take care of proper libraries discovery.

**Comment by ajoubertza** [comment]
Hi @stanislaw55. 
Sorry for delay on this one.  OK, so you have manually installed a newer version of Boost (Centos 7 comes with 1.53).  That's a bit harder to handle than just the standard version for each major OS.  

Yes, the logic for discovering the platform, libraries, etc. is in `setup.py`.  Using CMake could help, and yes we are using it for the Windows compilation, but the boost version is almost hard coded in there.   If you can propose something with CMake that solves the problem on Linux, great!  I don't know much about it.

**Comment by ajoubertza** [comment]
@stanislaw55  Would you mind testing the branch from the linked PR, please?

Also note that if you have a custom boost installation, the `BOOST_ROOT` and newly added `BOOST_LIB` environment variables may need to be set when running `python setup.py build`.

**Comment by ajoubertza** [comment]
Fixed in PR #335.
