### ISSUE TITLE
get_device_attribute_list and pipe methods missing from Database interface

### ISSUE THREAD

**Issue by lorenzopivetta** [tango-controls/pytango#313]
Seems that the method _get_device_attribute_list_ is missing from Database interface (db.py)

**Comment by ajoubertza** [comment]
@lorenzopivetta I think it will be easy for me to add it in.  Are there any other useful database methods you notice are missing?

Here are the C++ methods:  https://github.com/tango-controls/cppTango/blob/tango-9-lts/cppapi/client/Database.h

And the PyTango methods:  https://github.com/tango-controls/pytango/blob/develop/tango/db.py

**Comment by lorenzopivetta** [comment]
@ajoubertza A quick search shows all the Pipe related methods are missing:
_get_device_pipe_list, get_device_pipe_property, put_device_pipe_property, delete_device_pipe_property, get_class_pipe_property, put_class_pipe_property, delete_class_pipe_property, get_class_pipe_list_
Not a short list... but would be useful to add.

**Comment by grm84** [comment]
@ajoubertza @lorenzopivetta I'll add all of these to the pybind branch.
