### ISSUE TITLE
exception: No module named 'sphinx.ext.pngmath'

### ISSUE THREAD

**Issue by delleceste** [tango-controls/pytango#320]
Building PyTango from source, I get the exception in the subject.
It looks like pngmath has to be replaced with imgmath.

G.

**Comment by ajoubertza** [comment]
Hi @delleceste.  Thanks for the report, but I don't see pngmath in the codebase, only imgmath:  
https://github.com/tango-controls/pytango/blob/682dc950d871050eb9f8ab3684048171ae6510e2/doc/conf.py#L38

Are you using the latest code from the develop branch?  I'm also not sure why you would need to be building the docs locally - they are on [readthedocs](https://pytango.readthedocs.io).
