### ISSUE TITLE
PyTango  documentation does not state which Python minor version is supported

### ISSUE THREAD

**Issue by delleceste** [tango-controls/pytango#321]
On Python 3.7 I am unable to import PyTango.
I get several exceptions concerning asyncio, concerning the removal of the async method.
Thanks for any update.
In the documentation there is no indication of the supported Python minor version.

**Comment by ajoubertza** [comment]
Python 3.7 is supported - we do include the versions in setup.py, so they appear on [PyPI](https://pypi.org/project/pytango/).  As commented in issue #319 - I don't think the latest source is being used.
