### ISSUE TITLE
PyTango slow installation [Improvements]

### ISSUE THREAD

**Issue by mmphego** [tango-controls/pytango#323]
Running `pip install pytango` usually takes over 10min depending on one's system as it tries to recompiles the c/c++ files. However, the installation speed can be improved by publishing pytango wheel as well as the tarball.

See: [python-wheel](https://pythonwheels.com/)

# To reproduce

```bash
$ python setup.py sdist bdist_wheel
$ twine upload dist/*
```

By install pytango from wheel, this took just under 10 seconds.
![image](https://user-images.githubusercontent.com/7910856/71085069-4f2bab00-219f-11ea-9066-cfeea9964a53.png)

**Comment by ajoubertza** [comment]
I agree that the build time is slow.  It would be nice to use a wheel, but won't the resultant binary be tightly coupled to the version of the cppTango runtime and other dependencies installed on the build system (e.g. boost, omniorb and zeromq)?  I'm wondering if this wheel could be safely used on any version of Linux, where the source build could be done.  It would also need to work inside a Conda environment.

For Windows we already have a binary package, but it is tightly couple to the cppTango version.

**Comment by mmphego** [comment]
Not sure if it's possible to generate multiple wheels that are dependent on specific runtimes.

Saw some examples here: https://python-packaging-tutorial.readthedocs.io/en/latest/binaries_dependencies.html#build-components-and-requirements

If that fails, I suppose we will need to compile pytango each time one installs it.
