### ISSUE TITLE
get_device_properties not executed during init_device

### ISSUE THREAD

**Issue by stanislaw55** [tango-controls/pytango#328]
Hello
I have encountered following bug
during execution of `init_device` in Python 2.7, method `get_device_properties` is executed.
However, when executing server using Python 3.6, this method is not executed.

Have someone encountered such bug? What may cause this?

**Comment by ajoubertza** [comment]
@stanislaw55 I tried to reproduce that in the PyTango test suite, but it doesn't fail on any of the versions we test (2.7, 3.5, 3.6, 3.7).  See PR #329. 
Test results here: https://travis-ci.org/tango-controls/pytango/builds/645635870.

Can you submit basic example code showing this problem?  And the output of:
`python -c "import tango; print(tango.utils.info())"`

**Comment by stanislaw55** [comment]
Hi @ajoubertza 
thanks for exhaustive tests! This indicates that something is wrong with my setup. Below I attach output of command:
Python 2.7.5
```bash
PyTango 9.2.2 (9, 2, 2)
PyTango compiled with:
    Python : 2.7.5
    Numpy  : 1.16.4
    Tango  : 9.2.5
    Boost  : 1.53.0

PyTango runtime is:
    Python : 2.7.5
    Numpy  : 1.16.4
    Tango  : 9.2.5
    Boost  : 0.0.0

PyTango running on:
('Linux', 'd5aca464f013', '5.4.12-100.fc30.x86_64', '#1 SMP Wed Jan 15 00:38:53 UTC 2020', 'x86_64', 'x86_64')
```
(strangely, this does not find installed boost version - however, I've seen issue about that. I've checked and installed boost version is 1.53.0)

Python 3.6.8
```bash
PyTango 9.2.5 (9, 2, 5)
PyTango compiled with:
    Python : 3.6.8
    Numpy  : 1.12.1
    Tango  : 9.2.5
    Boost  : 1.69.0

PyTango runtime is:
    Python : 3.6.8
    Numpy  : 1.12.1
    Tango  : 9.2.5
    Boost  : 0.0.0

PyTango running on:
uname_result(system='Linux', node='d5aca464f013', release='5.4.12-100.fc30.x86_64', version='#1 SMP Wed Jan 15 00:38:53 UTC 2020', machine='x86_64', processor='x86_64')
```
(as above, in this case also version of installed boost is not listed, however it is the same as the build - 1.69.0)

My current guess is that there's something wrong with `Device` class initialisation in derived class. Will check and report back

**Comment by ajoubertza** [comment]
OK, thanks @stanislaw55.  If your problem wasn't Python version specific, then I'd guess that your Device is overriding `init_device` and not calling the super class's version.  But since it works in Python 2, that may not be the case.

**Comment by stanislaw55** [comment]
Hi,
I managed to resolve issue. It was caused by wrong call to super class. For future references:
this is the form that works and should be used
```python
super().init_device()
```
In my case, there was some old parameter to `super` call left over by migration from Python2

**Comment by ajoubertza** [comment]
Great - thanks for the feedback @stanislaw55
