### ISSUE TITLE
Green mode plugin system

### ISSUE THREAD

**Issue by stanislaw55** [tango-controls/pytango#336]
Hi,
I was thinking about Green Modes i PyTango. It is big amount of work to keep all already present green mode working with changes added to PyTango main library.

What do you guys think about making them plugins? They could use namespace packages or any other mechanism. There's nice documentation in [Python docs](https://packaging.python.org/guides/creating-and-discovering-plugins/). PyTango library could provide proper interface for plugins to implement and extract them to another repositories, as different packages. AsyncIO green mode implementation could be kept as 'standard implementation' and example for other plugins. This would also enable adding other framework like curio or trio without the need to modify PyTango itself.

Cheers

**Comment by ajoubertza** [comment]
Hi @stanislaw55 

> It is big amount of work to keep all already present green mode working with changes added to PyTango main library.

I'm not sure that's the case.  There has been hardly any maintenance required on these for the last year.

> What do you guys think about making them plugins? 

Plugins are an interesting idea, although getting that set up is some effort initially.  And then people would ask the plugin authors if they think the plugins are production ready.  Wouldn't having separate plugin developers/repos also fragment the development community?  I'd prefer that the effort that developers would put into plugins just to be put into contributing directly to PyTango instead.
  
> adding other framework like curio or trio

I like what I've seen about trio.
