### ISSUE TITLE
Attribute decorators

### ISSUE THREAD

**Issue by stanislaw55** [tango-controls/pytango#338]
Hi,
according to docs, it's currently possible to have syntax like this
```python
class PowerSupply(Device):
    def init_device(self):
        Device.init_device(self)
        self._current = -1

    @attribute(label="Current", unit="mA", dtype=int)
    def current(self):
        return self._current

    @current.write
    def current(self, current):
        self._current = current
```

what about extending attribute class to have syntax like this

```python
class DecoratorTest(Device):
    def init_device(self):
        Device.init_device(self)
        self._current = -1

    current = attribute(label="Current", unit="mA", dtype=int)

    @current.getter
    def cur_read(self):
        return self._current

    @current.write
    def cur_write(self, current):
        self._current = current

    @current.is_allowed
    def cur_allo(self, req_type):
        return True
```

**Comment by ajoubertza** [comment]
Hi @stanislaw55 

Maybe, but can you provide some detailed motivation?   What is the benefit, and/or what problems with the current implementation options does this solve?

**Comment by stanislaw55** [comment]
Hi @ajoubertza 
There are no problems with current implementation. However, I think that example I provided above would make syntax of DeviceServers more Pythonic by extending already existing mechanism of decorators
