### ISSUE TITLE
no database -nodb option

### ISSUE THREAD

**Issue by dschick** [tango-controls/pytango#353]
Hi,

I am currently developing a DS on a raspi and would like to test it without the need for a connection to a Tango-DB on a remote host.
I found the `-nodb` option in the [TANGO documentation](https://tango-controls.readthedocs.io/en/latest/administration/deployment/without-sql-db.html).
But when I start my DS with the following command:
`./plasma-debris-protector.py raspi -nodb -dlist id12/motor/1`
I do get the following error:
```
Missing ORB endPoint specification
usage :  PlasmaDebrisProtector instance_name [-v[trace level]] [-file=<file_name> | -nodb [-dlist <device name list>] ]
```

Otherwise the DS works fine in connection with the Tango DB.
I am using PyTango 9.2.5 from the raspi repos.

Best

Daniel

**Comment by dschick** [comment]
okay, found the answer to my own question.
It was obviously not a pytango but a tango issue.
The documenation was a bit thin at that point.
By adding ` -ORBendPoint giop:tcp::10000` to the command for starting the DS it is working.

**Comment by ajoubertza** [comment]
Hi @dschick 

Glad you got it sorted out.  Another convenient method to do this is the using the [`DeviceTestContext`](https://github.com/tango-controls/pytango/blob/70ef4df598b0309213112991be950e9613be8256/tango/test_context.py#L438), which we normally use to launch device servers during automated tests.   It can be used from the command line, something like this:

```
python -m tango.test_context plasma-debris-protector.PlasmaDebrisProtector --host 127.0.0.1
```

A full example [here](https://github.com/ajoubertza/icalepcs-workshop/blob/gh-pages/slideshow.md#server).

And the command line arguments for v9.2.5 can be seen [here](https://github.com/tango-controls/pytango/blob/2ec05cde5ac63db6b9b024c60207fa1bb011330e/tango/test_context.py#L282).

**Comment by dschick** [comment]
great, that is even more convinient.
Maybe it it worth putting this a bit more prominant into the docs?

many thanks!

**Comment by andygotz** [comment]
I agree this should be made visible in the documentation. I have also created an issue #354 to improve the command line options and help

**Comment by dschick** [comment]
great! I guess this will help many users.

Many thanks for the prompt replies
