### ISSUE TITLE
Dynamic attributes with write methods

### ISSUE THREAD

**Issue by TNoga0** [tango-controls/pytango#356]
Hello,

I'm wondering if there is a simple way to implement a writing method for dynamically generated attribute that takes the value as argument (or allows for user input).

So far I've been using Attr's get_write_value() method - example below: 
```
def write_analogOutput(self, attr) -> None:
        elem = attr.get_name().split("_")[1]
        value = attr.get_write_value()
        self.write_register(elem, self.decode_value(value, elem, `0))
```
...but the docs say it's deprecated, so I'm looking for another solution.

I'd be grateful for any help.

**Comment by ajoubertza** [comment]
Hi @TNoga0
 
I'm not sure.  Can you provide a link to where it says it is deprecated?  

I recently added [a test](https://github.com/tango-controls/pytango/blob/70ef4df598b0309213112991be950e9613be8256/tests/test_server.py#L278-L304) that uses that method too...

**Comment by ajoubertza** [comment]
OK, I have found the deprecation note:
https://github.com/tango-controls/pytango/blob/70ef4df598b0309213112991be950e9613be8256/tango/device_server.py#L1984-L1986

Note that there are two versions of the function, only the first one is deprecated. 

Basically it says **DON'T** do it this way: 
```python
def write_analogOutput(self, attr) -> None:
    elem = attr.get_name().split("_")[1]
    deprecated_way_to_get_values = []
    attr.get_write_value(deprecated_way_to_get_values)
    value = deprecated_way_to_get_values[0]
    self.write_register(elem, self.decode_value(value, elem, 0))
```

**Comment by ajoubertza** [comment]
@TNoga0 Does this answer your question?

**Comment by ajoubertza** [comment]
No response, so closing old ticket.
