### ISSUE TITLE
Device.get_attribute_config() requires byte-string

### ISSUE THREAD

**Issue by dschick** [tango-controls/pytango#361]
Hi,

I encountered a Segmentation Fault when trying to call the `get_attribute_config()` method within a Device Class using native Py3 unicode strings.
See more details here: https://www.tango-controls.org/community/forum/c/development/python/get_attribute_config/
The workaround is to hand a byte-string instead of a native Py3 unicode string to the method, so
`get_attribute_config(b"attribute_name")` instead of `get_attribute_config("attribute_name")`

I am using PyTango 9.2.5 but it seems also to occur for PyTango 9.3.2.

**Comment by ajoubertza** [comment]
Thanks @dschick.  I made a fix for this in the linked PR.
