### ISSUE TITLE
DeviceProxy AttributeError: cause is lost

### ISSUE THREAD

**Issue by woutdenolf** [tango-controls/pytango#364]
When a device is not running, trying to get an attribute raises `AttributeError` while losing the cause of this error. Why not use `raise AttributeError() from cause`?

```python
# tango.device_proxy
__DeviceProxy__getattr(self, name):
    cause = None
    ...
    try:
        self.__refresh_cmd_cache()
    except Exception as e:
        cause = e
    ...
    raise AttributeError(name) from cause
```

**Comment by ajoubertza** [comment]
@woutdenolf That sounds like a good idea.  Thanks.
