### ISSUE TITLE
Access violation - no RTTI data!

### ISSUE THREAD

**Issue by Ingvord** [tango-controls/pytango#368]
Dear PyTango Gurus,

Playing with PyTango on Windows (... shame on me) I have encountered the following error when starting my test Tango server (PowerSupply from the docs)

```
PyDS: PowerSupply: An error occured in the constructor:
Access violation - no RTTI data!
```

```python
Python 3.6.2 |Anaconda, Inc.| (default, Sep 19 2017, 08:03:39) [MSC v.1900 64 bit (AMD64)]
>>> import tango
>>> print(tango.Release.version)
9.3.2
```

Any ideas? Thanks!

**Comment by ajoubertza** [comment]
Hi @Ingvord 

(not too much shame!)

Might that problem be related to the general failure of 9.3.2 on Windows?  See #355. 
Does 9.3.1 work?

**Comment by Ingvord** [comment]
@ajoubertza 

You are totally right. With 9.3.1 (`pip install pytango==9.3.1`) it works!

**Comment by Ingvord** [comment]
Furthermore it is advised to use Anaconda to set up Python 3.6 as with newer Python versions PyTango seems to be in a non-great relationship
