### ISSUE TITLE
Take attribute and property type from type hint

### ISSUE THREAD

**Issue by stanislaw55** [tango-controls/pytango#373]
Hi,
I wanted to share an idea. Right now, when addint attribute (or property) in device class, one need to specify it in constructor like this:

```python
attr = attribute(
        dtype="DevState",
        label="Heat Absorber",
        access=AttrWriteType.READ,
        doc="State of the Heat Absorber",
)
```

when adding type hint support (for mypy, in example), one has to duplicate the type definition like this

```python
attr: DevState = attribute(
        dtype="DevState",
        label="Heat Absorber",
        access=AttrWriteType.READ,
        doc="State of the Heat Absorber",
)
```

It would be cool to just define attribute like this

```python
attr: DevState = attribute(
        label="Heat Absorber",
        access=AttrWriteType.READ,
        doc="State of the Heat Absorber",
)
```

So type is taken from Python's type hint. It would be super nice if it would work with spectrum and image attributes

```python
attr: List[float] = attribute(
        label="Bar",
        access=AttrWriteType.READ,
        doc="Bar attribute",
)
attr: List[List[bool]] = attribute(
        label="Foo",
        access=AttrWriteType.READ,
        doc="Foo attribute",
)
```

and even `max_dim_x` and `max_dim_y` when using `Tuple`

**Comment by ajoubertza** [comment]
@stanislaw55 Thanks for sharing an interesting idea - I can see how the duplication is undesirable.  I have some comments:
- What is the benefit of a type hint for `attr` in the examples above?  In a device it would only ever be assigned to once, so it doesn't provide any type safety.  We also wouldn't typically access the attribute object, `self.attr`, within a device.
- Type hints may be useful for properties, as we do access them within the device.  However, reading properties provide would generally provide simpler types, like a string or list of strings, so manual type annotation wouldn't be too verbose.
- Would type hints be necessary when using the decorator syntax for attributes, and how would that be handled?
- The biggest issue I see is that creating run-time functionality solely from type hints seems to go against the goals of [PEP484](https://www.python.org/dev/peps/pep-0484/#rationale-and-goals) and [PEP526](https://www.python.org/dev/peps/pep-0526/#non-goals).  Have you seen it used in this way in other Python projects?

**Comment by stanislaw55** [comment]
Hi @ajoubertza 
I'll answer in the same order as you asked

* Indeed, accessing attributes is rare but it would be nice to have coherent syntax with properties.
* Verbosity is not a problem. Repetition and possible slight changes in future may cause problems. I.e. changing property type from int to float or the other way around would require change in two places rather than one.
* That's good question, I haven't thought about that. Maybe just adding type hints like in normal functions would be enough but I'm not sure.
* Although I did not see it in other Python projects, I think it could be minor feature. Type declared in `property` or `attribute` would always have bigger priority than type hint, if both provided. In case only type hint is provided, it would take it as a type. Otherwise fail as always.

**Comment by AntoineDupre** [comment]
Hi @stanislaw55 

I don't think that `mypy` will work because `attr` is not a `DevState` but it is a `tango.server.attribute`.
It's the same for properties, they are in the class level defined as: `tango.server.device_property`.

It can look like a good idea if we consider only the tango context (attributes are statically typed) but it is lying  from a python point of view. 

Moreover, i think it can be quiet confusing adding type hints in the class definition for attributes and properties because when a device class is instantiated, the same names are used but for different objects (device_property are converted to properties' value and attribute are converted to `_tango.Attribute`).
