### ISSUE TITLE
[question] Tango is not initialised

### ISSUE THREAD

**Issue by woutdenolf** [tango-controls/pytango#374]
When we get the message `Tango is not initialised !!! Exiting` in stderr what does this mean? Looking at the code this seems to occur when the `Util` singleton object is not instantiated. What are the possible causes?

We do use `ApiUtil.cleanup()` in our test suite after every test (to prevent fd leaks, see issue #324). Is this the reason? And if it is, why doesn't it occur systematically (only once in a while). Who is in charge of instantiating the `Util` singleton?

**Comment by ajoubertza** [comment]
@woutdenolf Sorry, I don't have any ideas about the cause.

Looking at the cppTango code, `ApiUtil` is for [clients](https://github.com/tango-controls/cppTango/blob/4d2ad6555fd6bc6e6603406ea83b6ed0ed797eb3/cppapi/client/ApiUtil.h#L40-L46), while `Util` is for [servers](https://github.com/tango-controls/cppTango/blob/4d2ad6555fd6bc6e6603406ea83b6ed0ed797eb3/cppapi/server/utils.h#L124-L137).  So I'm not sure if the `ApiUtil.cleanup()` is the problem.  Could be.

From the PyTango code, if I start new device server, the first hit I get for the `Util` singleton creation is [here](https://github.com/tango-controls/pytango/blob/148e1322ba652040ec8a67c351d5285c6e47cfc6/tango/server.py#L1331), called from class method [`tango.server.Device.run_server`](https://github.com/tango-controls/pytango/blob/148e1322ba652040ec8a67c351d5285c6e47cfc6/tango/server.py#L647).

Are you using the [`DeviceTestContext` ](https://github.com/tango-controls/pytango/blob/148e1322ba652040ec8a67c351d5285c6e47cfc6/tango/test_context.py#L438)for your tests?

What versions of cppTango and pyTango are you using? Output from
`python -c "import tango; print(tango.utils.info())"` might be useful.

**Comment by woutdenolf** [comment]
Thanks for the quick reply! This is the version info:

```python
PyTango 9.3.1 (9, 3, 1)
PyTango compiled with:
    Python : 3.7.4
    Numpy  : 1.11.3
    Tango  : 9.3.2
    Boost  : 1.67.0

PyTango runtime is:
    Python : 3.7.6
    Numpy  : 1.19.1
    Tango  : 9.3.4
    Boost  : 0.0.0

PyTango running on:
uname_result(system='Linux', node='lid21data', release='4.19.0-6-amd64', version='#1 SMP Debian 4.19.67-2 (2019-08-28)', machine='x86_64', processor='')
```

The tango servers (and the database) are run as subprocesses for the tests (so we don't use DeviceTestContext). So then `ApiUtil.cleanup()` should have nothing to do with it.

**Comment by woutdenolf** [comment]
Thanks for the quick reply! This is the version info:

```python
PyTango 9.3.1 (9, 3, 1)
PyTango compiled with:
    Python : 3.7.4
    Numpy  : 1.11.3
    Tango  : 9.3.2
    Boost  : 1.67.0

PyTango runtime is:
    Python : 3.7.6
    Numpy  : 1.19.1
    Tango  : 9.3.4
    Boost  : 0.0.0

PyTango running on:
uname_result(system='Linux', node='lid21data', release='4.19.0-6-amd64', version='#1 SMP Debian 4.19.67-2 (2019-08-28)', machine='x86_64', processor='')
```

The tango servers (and the database) are run as subprocesses for the tests.

**Comment by ajoubertza** [comment]
> The tango servers (and the database) are run as subprocesses for the tests (so we don't use DeviceTestContext). So then ApiUtil.cleanup() should have nothing to do with it.

I'm not sure if you mean that because you are not using `DeviceTestContext` that implies that `ApiUtil.cleanup()` is not the cause?  `DeviceTestContext` can also run the devices in a subprocess.

PR #260 might give you some more clues (see PR comments and doc updates), even though it was focused on the `ApiUtil.cleanup()`.  It reminds us that subprocess inherit from their parents:

> your child process inherits the context from your parent process,
i.e. open file descriptors, the TANGO and the CORBA state.
Sharing the above objects between the processes may cause unpredictable
errors, e.g. *TRANSIENT_CallTimedout*, *unidentifiable C++ exception*.
Therefore, when you start a new process you must reset CORBA connection

Maybe two subprocesses inherit the same `Util` instance (e.g., if parent already created it).  Then parent, or one subprocess could release the instance that another subprocess needs.  The `Util` object is ultimately allocated/deallocated by the cppTango code, so could it end up being shared across subprocesses?

If you can provide an example that reproduces the problem reliably, then we could investigate further.  Otherwise, you are on your own, unfortunately.

**Comment by woutdenolf** [comment]
> I'm not sure if you mean that because you are not using `DeviceTestContext` that implies that `ApiUtil.cleanup()` is not the cause?

Sorry I wasn't clear. If I understand well `ApiUtil` (client side) and `Util` (server side: subprocess in our case) are two different things (I wasn't aware). But maybe assuming that `ApiUtil.cleanup()` does not affect `Util` in a subprocess was jumping to conclusions.

> DeviceTestContext can also run the devices in a subprocess.

In that case I should investigate (I wasn't aware of this). We use pytest fixtures for the different devices. Can we use multiple `DeviceTestContext` or are we forced to use only one `MultiDeviceTestContext`?

> If you can provide an example that reproduces the problem reliably, then we could investigate further. Otherwise, you are on your own, unfortunately.

Yes I know. It's a rather complex test suite and even in its context, the error is not reproducible (e.g. happens only on our CI machines). If I manage to create a minimal example, I'll certainly post it.

**Comment by bourtemb** [comment]
> When we get the message `Tango is not initialised !!! Exiting` in stderr what does this mean? Looking at the code this seems to occur when the `Util` singleton object is not instantiated. What are the possible causes?

The Tango::Util::instance is normally created when Tango::Util::init(int argc, char ** argv[]) is invoked.
So, I would say that the probable cause is that Tango::Util::init(int argc, char ** argv[]) was not invoked.

> We do use `ApiUtil.cleanup()` in our test suite after every test (to prevent fd leaks, see issue #324). Is this the reason? 

I don't think this is linked. ApiUtil is a different class. Its instance is different than the one from Tango::Util

> Who is in charge of instantiating the `Util` singleton?

From what I see from the code, it seems to be Tango::Util::init(int argc, char ** argv[]) method

**Comment by bourtemb** [comment]
The Doxygen documentation confirms what I was writing:

https://tango-controls.github.io/cppTango-docs/classTango_1_1Util.html#a577119e32b43b1344d6f9ef37f587472

>  If the class has not been initialised with it's init method, this method print a message and abort the device server process

**Comment by ajoubertza** [comment]
> From what I see from the code, it seems to be Tango::Util::init(int argc, char ** argv[]) method

This happens in the PyTango extension code [here](https://github.com/tango-controls/pytango/blob/03c46a9aced7a725774ac8c60636f889f2dae47f/ext/server/tango_util.cpp#L90).  That should be called automatically.  Normally happening if `tango.server.Device.run_server` is used, as mentioned in an earlier comment.

**Comment by woutdenolf** [comment]
I can confirm it happens when calling `tango.Util(args)` on the server side (done in a subprocess of a test suite). We wait for the database to be online before starting the subprocess. "Online" means: pingeable, state=ON and we can get the list of exported devices from `sys/database/2`. Still can't find a way to reproduce it outside of our context.

Edit: for reference if the database is not running  `tango.Util(args)` prints `Can't build connection to TANGO database server, exiting`. So that's a different thing.

**Comment by woutdenolf** [comment]
Are `PyTango.Util.init(args)` and `PyTango.Util(args)` equivalent?

**Comment by ajoubertza** [comment]
> I can confirm it happens when  ...

From that comment, it sounds like the parent process that is checking the database will already have an instance of `Util` and be "doing TANGO stuff" before the subprocess is launched.  The subprocess would inherit the parent process's context, which would include the TANGO and the CORBA state.  As noted earlier in this discussion, that could cause unpredictable results.

Is it possible to change your tests so that only the subprocesses have TANGO/CORBA state, to help with the isolation?  I.e., the parent process does not use TANGO at all - only the subprocesses do.  In that you would have to use a subprocess to do the database online check.

Once all the subprocesses are launched, then it may be OK to use TANGO code in the parent process, as they all have their own contexts. 

> Are `PyTango.Util.init(args)` and `PyTango.Util(args)` equivalent?

It looks like it.  The `Util.__init__` method calls `Util.init` (if I'm understanding the Boost extension code correctly).

> Can we use multiple `DeviceTestContext` or are we forced to use only one `MultiDeviceTestContext`?

You should be able to use multiple of both.  Note that devices run via the test context are run in _nodb_ mode, which might not be what you want.

**Comment by woutdenolf** [comment]
We have one subprocess which runs the database and several other subprocesses which run the device servers.

> Is it possible to change your tests so that only the subprocesses have TANGO/CORBA state

The tests will need to use the tango devices (`DeviceProxy`) but we don't run any server in the main process.

1. What do you mean with `TANGO/CORBA state` actually?

2. How can I check where this `TANGO/CORBA state` is being instantiated? What instantiates it? Calling `Database()` or `DeviceProxy(dev_name)` or even `import tango`? Are you talking about the `Util` singleton? Or other things as well?

3. Does `tango.ApiUtil.cleanup()` apply to the `ApiUtil` singleton or does it cleanup all `TANGO/CORBA state` (whatever that is)?

Edit: to elaborate a bit more. We have several pytest fixtures which setup each individual test. Each fixture starts the database or a tango server an yields one or more device proxies (pinged and state checked with a timeout). So calling `tango.ApiUtil.cleanup()` before each subprocess is not an option. We do have a cleanup fixture which does `tango.ApiUtil.cleanup()` after every test.

Edit: https://pytango.readthedocs.io/en/stable/howto.html
I must have misread this. It seems I need to call `tango.ApiUtil.cleanup()` in each subprocess that starts a tango server?

**Comment by ajoubertza** [comment]
1. It isn't that clear to me either, but see this [comment](https://github.com/tango-controls/pytango/issues/259#issuecomment-463729156), and also cppTango issue linked in that same discussion thread.  That is where I got it from.
2. I don't know how to check it.  From the linked discussion threads, calling `DeviceProxy(...)` or `Database()` would do it.  From the cppTango code, not only do they access the `ApiUtil` instance, but there are code paths where they can access the `Util` instance (if the client is in the same process as the server).  The check for "in server" [considers](https://github.com/tango-controls/cppTango/blob/5fad4ed12ee7569616c546a5d81ddf7a0e0f4978/cppapi/client/api_util.cpp#L95) if the `Util` singleton has been constructed. 
3. It only applies to the `ApiUtil`.  It will call this [destructor](https://github.com/tango-controls/cppTango/blob/5fad4ed12ee7569616c546a5d81ddf7a0e0f4978/cppapi/client/api_util.cpp#L174).  The `Util` class has its own [destructor](https://github.com/tango-controls/cppTango/blob/5fad4ed12ee7569616c546a5d81ddf7a0e0f4978/cppapi/server/utils.cpp#L1576) (but no cleanup method we can call).
4. From the linked discussions, `ApiUtil.cleanup()` would need to be called at the start of the subprocess, _not before_ each subprocess.  The idea is that the subprocess no longer has open file descriptors, etc., related to TANGO/CORBA that it inherited from its parent.

**Comment by woutdenolf** [comment]
In the end the issue may have been the same as:

https://www.tango-controls.org/community/forum/c/platforms/gnu-linux/device-server-gets-stuck-then-works-as-expected/

In our case we had CI in docker containers on virtual machines and there was not enough entropy. I have no idea what this has to do with TANGO or CORBA but it seems affected by it. The solution:

```
docker run -v /dev/urandom:/dev/random 
```
