### ISSUE TITLE
Polling period does not update / how to do proper polling

### ISSUE THREAD

**Issue by EmCeBeh** [tango-controls/pytango#383]
Hi,
as far as I understand, I would do polling like this:

I created a device server with the attribute `value` and a variable `_internalValue

```python
value = attribute(label="value", dtype=float)

_internalValue = 0

def read_value(self):
    return self._internalValue

@command(polling_period=2000)
def update_internalValue(self):
    self._internalValue = np.random.random()
```

The extra function I create, because later the value will of course not be random but come from a device with a serial port and a very slow connection. The value should update every two seconds. And all the clients can access the last internally stored value to not overload the serial connection.

First question: is this correct?
Second question: If yes, then why - when I stop the server, change the `polling_period=5000` - the value is still polled every 2000 ms?

I can now access the server via e.g. `Jive` and delete the polling and then restart the server again and it does NOW poll it at 5000ms, but shouldn't the start of the server overwrite the old polling period?

Thanks!
Martin :)

My Setup uses:
```python
PyTango 9.2.5 (9, 2, 5)
PyTango compiled with:
    Python : 3.7.1
    Numpy  : 1.15.4
    Tango  : 9.2.5
    Boost  : 1.67.0
PyTango runtime is:
    Python : 3.7.3
    Numpy  : 1.16.2
    Tango  : 9.2.5
    Boost  : 0.0.0
```

**Comment by AntoineDupre** [comment]
Hi @EmCeBeh 

For your information, you can directly put some polling on the attribute itself. 
```python
class Test(Device):
     
     _internalValue = 0

    @attribute(dtype=float, label="value", polling_period=2000)
    def valve(self):
        self._internalValue = np.random.random()
        return self._internalValue
```

Internally the polling thread will execute every 2 seconds the read method and feed a cache for this attribute. Clients will now get the cached value when then do a read query.

About your second question. The `polling_period` argument value is used only if there is no polling period defined in the tango database. As soon as you change the polling period from jive, the new value is stored in the tango database and will be applied on device server startup.

**Comment by EmCeBeh** [comment]
Thanks a lot! Also for clarification this is equivalent to
```python
class Test(Device):
     
     _internalValue = 0

    value = attribute(dtype=float, label="value", polling_period=2000, access=AttrWriteType.READ)

    def read_value(self):
        self._internalValue = np.random.random()
        return self._internalValue
```
right?

**Comment by AntoineDupre** [comment]
Yes it is equivalent
