### ISSUE TITLE
typo in get_server_info documentation

### ISSUE THREAD

**Issue by abdomit** [tango-controls/pytango#392]
There is a typo in the documentation of `get_server_info` defined in `tango/db.py:1572`

the doc says:
`name of the server to be unexported with format: <server name>/<instance>`

it should be:
`name of the server with format: <server name>/<instance>`

**Comment by ajoubertza** [comment]
Thanks for the note, @abdomit.  Would you mind submitting a pull request with a fix?

**Comment by abdomit** [comment]
No problem: #393

**Comment by abdomit** [comment]
Thanks for the merge
