### ISSUE TITLE
Events stops to work after a while

### ISSUE THREAD

**Issue by reszelaz** [tango-controls/pytango#394]
Hi all,

I have found a strange bug, not sure if it comes fron PyTango or from cppTango, for the moment I create it here.

Short description:

The architecture is as following. We have one DS called `DeviceLostEvent` which exports one device of the `DeviceLostEvent` class. This device has one command `cmd` which when executed change's device state to MOVING and pushes the state event. Just after that it starts a thread which will sleep a little and again change and push state to ON.

The client starts a `long_job()` in a thread which will continuously execute the command based on the events being received. Then it continuous in the main thread to execute `short_job()` which will subscribe and unsubscribe to another attribute's events. The `long_job()` stops receiving events after exactly 500 iterations!

The code to reproduce it more detailed description can be found in:  https://github.com/reszelaz/test-tango-lostevent

Thanks in advance for looking into it!

**Comment by bourtemb** [comment]
Hi @reszelaz ,
Could you tell us what versions of cppTango, PyTango and ZMQ you are using?

**Comment by reszelaz** [comment]
The issue is not reproducible using the latest packages of cppTango and PyTango.
Sorry for the spam.

**Comment by bourtemb** [comment]
@reszelaz, you probably faced this bug: https://github.com/tango-controls/cppTango/issues/444

**Comment by reszelaz** [comment]
Yeap, it must be this one. I fell into the same trap as 2 years ago:)
I was continuing investigation on #315. I'm not 100% sure if what we experience at our beamlines is #315 or another bug - the backtraces that I collect at the beamline and using the example are not exactly the same. I will keep trying to get some more information.
