### ISSUE TITLE
Are DynamicCommands not suported in python / pythonHL? (Pogo says so)

### ISSUE THREAD

**Issue by sergirubio** [tango-controls/pytango#396]
Hi,

I am not sure whether it is a PyTango or a Pogo issue.

When generating a Python device server with Dynamic Commands in Pogo, this message appears:

      "Dynamic Commands are not supported in python" 

If PythonHL is selected instead then no warning appears, but commands are not added to the generated source.

Sergi

**Comment by ajoubertza** [comment]
Hi @sergirubio 

They are supported.  See a PyTango example [here](https://github.com/tango-controls/pytango/blob/3f5e3ec8440267fb72f501d777d48c28f35b13ba/examples/interfacechangeEvents/IfchangeServer.py#L52-L57) for high level API.  In that example, I notice the `from tango.server import DispLevel` must be changed to `from tango import DispLevel`.

Another place we used it is in [tango-simlib](https://github.com/ska-sa/tango-simlib/blob/a5ece2b83ce8a38b30d88ad62c55506e09b77e1b/tango_simlib/tango_sim_generator.py#L289-L293).

I'm not sure if it can be used with the classic API.

**Comment by sergirubio** [comment]
Hi Anton,

So, it seems that is not a PyTango bug but a Pogo bug  instead; it should generate dynamic commands templates for PythonHL

You can close the ticket and I'll open a new one in Pogo queue,

Sergi

**Comment by sergirubio** [comment]
Just for tracking: I added the issue in Pogo queue

https://github.com/tango-controls/pogo/issues/103
