### ISSUE TITLE
Gitlab Migration: Please log into GL with your GH account ASAP

### ISSUE THREAD

**Issue by bourtemb** [tango-controls/pytango#400]
Dear pytango participant (via commits, comments on issue or pull requests, issue creator),

If you have contributed in any way (commit, issue or Pull Request creation or comment) to pytango, please log into Gitlab.com using your Github account **ASAP**.
See https://github.com/tango-controls/TangoTickets/issues/47 for details.

Please click on the following link and add your github account name to this [framapad](https://mensuel.framapad.org/p/migration_ready_2548763689) when you've already done the login to Gitlab.com using your Github account:
https://mensuel.framapad.org/p/migration_ready_2548763689

Please note that login on gitlab.com using your Github account is safe and doesn't give your Github password to Gitlab.

For convenience, here is the list of contributors we could already find (and who did not signal they had done it yet for another repo):
- [ ] AntoineDupre
- [ ] @Athanaseus
- [x] @Diego91RA
- [x] DrewDevereux
- [ ] @EmCeBeh
- [ ] @HighwayStar
- [ ] @JagodaS
- [ ] JeanLucPons
- [ ] @Kamil2806
- [ ] KrystianKedron
- [ ] @LJBD
- [ ] @Limonkufu
- [x] @MikeFalowski
- [ ] @NexeyaSGara
- [x] PhilLAL
- [ ] @Val7
- [x] @abdomit
- [x] @adityadangeska
- [x] ajoubertza
- [ ] @alainbuteau
- [ ] @asoderq
- [x] @aureocarneiro
- [x] @bennofs
- [x] @birkenfeld
- [ ] @brickZA
- [x] daneos
- [x] delleceste
- [ ] @dnaudet
- [x] @dschick
- [ ] @efferre79
- [ ] @gcerretani
- [ ] @grm84
- [ ] hardion
- [ ] @hasrifa2003
- [ ] @hayg25
- [ ] @izadworny
- [ ] jairomoldes
- [ ] @johanfforsberg
- [ ] @jyotinpo
- [ ] @kklmn
- [ ] @laurent-claustre
- [ ] @ldoyle
- [x] lorenzopivetta
- [ ] lzytniak
- [ ] @meguiraun
- [ ] mguijarr
- [ ] @mmphego
- [ ] mrosanes
- [ ] @ohlssonm
- [ ] @oli506
- [ ] @piertoni
- [ ] piogor
- [ ] @rhomspuron
- [ ] @rile993
- [ ] @sbodomerle
- [x] @schooft
- [x] @sdebionne
- [ ] @sebastien-petitdemange
- [x] sergirubio
- [ ] @sk1p
- [ ] @spirit1317
- [ ] @stanislaw47
- [ ] stanislaw55
- [ ] tiagocoutinho
- [ ] @vallsv
- [ ] vxgmichel
- [ ] @weninc
- [x] wkitka
- [x] @woutdenolf
- [ ] @wyrdmeister

Thanks for your cooperation.

**Comment by ajoubertza** [comment]
The PyTango gitlab migration is planned for Thursday 28 January 2021, so last chance to do the steps above is 27 January 2021.
