### ISSUE TITLE
New release planned: v9.3.3

### ISSUE THREAD

**Issue by ajoubertza** [tango-controls/pytango#402]
This is to inform the community that a new release is being prepared.

- [x] Read steps in the how-to-contribute docs for making a release
- [x] Pull request to update changelog and bump version
- [x] Merge PR (this is the last PR for the release)
- [x] Merge develop into stable
- [x] Make sure Travis and Appveyor are OK on stable branch
- [x] Make sure the documentation is updated for stable (readthedocs)
- [x] Create an annotated tag from stable branch
- [x] Make sure the documentation is updated for release (readthedocs)
- [x] Upload the new version to PyPI
- [x] Bump the version with “-dev” in the develop branch
- [x] Create and fill in the release description on GitHub
- [x] Build conda packages
- [x] Advertise the release on the mailing list
- [x] Close this issue

**Comment by bourtemb** [comment]
I uploaded some pytango 9.3.3 conda packages on tango-controls conda channel.
Please report issues related to these pytango conda packages on https://github.com/tango-controls/pytango-conda-recipes git repository.

**Comment by ajoubertza** [comment]
Thanks for the Linux conda packages, @bourtemb.

**Comment by andygotz** [comment]
Hi @bourtemb , thanks a lot! Do you know what needs to be done to do the same for Windows?

**Comment by ajoubertza** [comment]
> Hi @bourtemb , thanks a lot! Do you know what needs to be done to do the same for Windows?

There is a repo related to that, although it isn't set up to do any automated building.  @andygotz  I suggest this discussion moves to an issue there, as this ticket is closed.
https://github.com/tango-controls/pytango-windows-conda-recipes
