### ISSUE TITLE
PyPI registration: new lowercase package name conflicts with the old one

### ISSUE THREAD

**Issue by vxgmichel** [tango-controls/pytango#49]
I just realized PyPI won't let me release `pytango-9.2.0`, because the new package name conflicts with the old one (`PyTango`):

```
Server response (403): Package name conflicts with existing package 'PyTango'
```

I'm opening a ticket on [PyPI support requests](https://sourceforge.net/p/pypi/support-requests/) (this has been done before for other projects, e.g. [pafy](https://github.com/mps-youtube/pafy/issues/56)).

**Comment by vxgmichel** [comment]
Reported, [see ticket 660](https://sourceforge.net/p/pypi/support-requests/660/).

**Comment by tiagocoutinho** [comment]
There has been some time since this issue is open in PyPi and no action has been taken on their side.
It would be nice to close this. It kind of blocks us from making new releases.

I think we can live with the original name PyTango. What do you think?

**Comment by vxgmichel** [comment]
Yes, it seems the person who took care of this kind of renaming for other projects is not working on PyPI any more... I think we can live with a camel case `PyTango` on PyPI, but I'd like to keep `pytango` as package name in `setup.py`. I'll run some tests to see it that causes any problem. Is that OK with you?

**Comment by vxgmichel** [comment]
I'm confused... I just uploaded `pytango-9.2.0` to PyPI and it worked, no `Server response (403)` this time.
Well, I guess it's good news! I also uploaded the windows binaries @NexeyaSGara sent me.

I'll merge PR #78. Maybe it's time to release `pytango-9.2.1`?
