### ISSUE TITLE
Server declared with python 3 typing

### ISSUE THREAD

**Issue by tiagocoutinho** [tango-controls/pytango#53]
It would be great if we could take advantage of python 3 `typing` hints to write PyTango servers.
Here is a concrete example:

``` python

from typing import List

from tango.server import Device, attribute, command


class PowerSupply(Device):

    @attribute(label='Voltage')
    def voltage(self) -> float:
        return 1.0

    @voltage.setter
    def voltage(self, new_voltage: float):
        pass

    @attribute
    def trend(self) -> List[float]:
        return range(10)

    @command
    def RampUp(self, target: float) -> str:
        return 'OK'
```

**Comment by johanfforsberg** [comment]
This would be really cool!

As a bonus we might be able to statically type check the code using MyPy, to catch bugs before runtime. I wonder how much of pytango would need to be type hinted for that to be useful...
