### ISSUE TITLE
Move to tango-controls group

### ISSUE THREAD

**Issue by tiagocoutinho** [tango-controls/pytango#55]
Hi,
We just finished a tango 10 workshop at ESRF with people from Alba, Soleil, and Elettra.

One of the decisions taken was that the official tango organization on github should be _tango-controls_.

They have asked that pytango moves to this organization.

**Comment by tiagocoutinho** [comment]
I can do it if nobody disagrees
FYI: the old link to this project will still work. It will just become an alias to the new one

**Comment by vxgmichel** [comment]
No problem! We'll also have to transfer the members to the new organization.

**Comment by tiagocoutinho** [comment]
Agree. I think there is no way to do it atomically so I propose to do it today 21-09, 17h CEST in two steps:
* move project
* invite people

Hopefully it will not disturb anyone

**Comment by johanfforsberg** [comment]
I have no objections.

**Comment by tiagocoutinho** [comment]
Ok, after a lot of delays I have done it. The team was recreated and members invited.
Fortunately the old github links point to the new project so +1 for github!
