### ISSUE TITLE
Dynamically creating enum attributes

### ISSUE THREAD

**Issue by johanfforsberg** [tango-controls/pytango#56]
I can't manage to dynamically create a DevEnum attribute in pytango 9. Statically defined enum attributes appear to work, but as far as I've been able to figure out, I should be able to do something like:

``` python
attr = tango.AttrData(
                "MyNiceEnum", None,
                attr_info=[
                    (
                        tango.DevEnum,
                        tango.SCALAR,
                        tango.READ
                    ), {
                        "enum_labels": ["A", "B", "C"]  # no workee!
                    }
                ])
self.add_attribute(attr, r_meth=self.read_MyNiceEnum)
```

The attribute gets added, but it does not have any labels configured.

**Comment by tiagocoutinho** [comment]
I believe this issue is coming from C++ tango. I will get back to you when I have a confirmation

**Comment by Athanaseus** [comment]
Hi @tiagocoutinho any confirmation that this issue comes from C++ tango?

**Comment by ajoubertza** [comment]
Fixed in linked PR.
