### ISSUE TITLE
Forwarded attributes API

### ISSUE THREAD

**Issue by tiagocoutinho** [tango-controls/pytango#7]
I propose to implement the new forward attributes feature in Tango 9 like this:

``` python
class D(Device):

    energy = attribute(label="Energy", forward=True)
```

`forward` keyword is `False` by default. When `forward=True` it should only accept `label` keyword. All other keywords should throw exception.

I am open to any comments/suggestions/proposals ?

**Comment by NexeyaSGara** [comment]
Hi,
Just some questions:
If the label is not correctly formatted or the attribute is not accessible, what will be the default behaviour ?
 - Attribute not added ?
 - Device in Fault ?

Another though:
In Pogo, the forwarded attributes are a new category and not a specific attribute.
So I'm thinking maybe making : 
energy = fw_attribute(label="Energy")
will be more pratical.

**Comment by tiagocoutinho** [comment]
Hi,

Since PyTango binds to C++, in case of error, the behavior would be the same as the C++ level.
I think it it good question. I could not find any reference in the C++ doc concerning error behavior on forward attributes. In the [Tango controls system handbook](http://ftp.esrf.fr/pub/cs/tango/tango_91.pdf), chapter *7.8 Forwarded attribute* you can find some information.

Concerning the API, honestly I don´t think that making code generation easier is a good reason for having a less cleaner API. Having said that, I don´t think your ``fw_attribute`` is specially bad. Personally I prefer the ``attribute(forward=True)`` API to the ``fw_attribute``. I don´t have strong feelings so if more people prefer your solution i am fine with it.

**Comment by johanfforsberg** [comment]
I don't have a strong opinion either, but I tend towards keeping the API simple to understand. Having different sets of allowed arguments depending on the value of one argument seems potentially confusing, so I think using a different function for forwarded attributes makes some sense. 

However I'm also a fan of explicit and obvious naming, so in that case I would prefer e.g. "forwarded_attribute" to "fw_attribute". TANGO already has its fair share of abbreviations :)

**Comment by vxgmichel** [comment]
@johanfforsberg  +1

**Comment by tiagocoutinho** [comment]
Ok, `forwarded_attribute` it will be!
Thanks for the input.

**Comment by NexeyaSGara** [comment]
I will implement it for next Pogo version

**Comment by tiagocoutinho** [comment]
Hi guys, sorry to come back again but I need to come back again to this API issue.

I think that applying a classifier (in this case `forwarded_` prefix) is not consistent with the current API.
If we apply this principle, this means that, for example, to declare an integer scalar attribute, the user would have to write something like `scalar_integer_attribute`.

So I changed my mind and now I do have a **strong** opinion in favor of `attribute(forwarded=True)` and against `forwarded_attribute`.

Still, if you maintain your votes for `forwarded_attribute`, they will be honored.

**Comment by NexeyaSGara** [comment]
Hi, 

For me, I think that Johan comment describes what I feel, but I don't think there is a lot of people reading this conversation. Maybe we need to ask this on the forum or the mailing list.

> johanfforsberg commented on 4 Mar
I don't have a strong opinion either, but I tend towards keeping the API simple to understand. Having different sets of allowed arguments depending on the value of one argument seems potentially confusing, so I think using a different function for forwarded attributes makes some sense.

However I'm also a fan of explicit and obvious naming, so in that case I would prefer e.g. "forwarded_attribute" to "fw_attribute". TANGO already has its fair share of abbreviations :)

**Comment by vxgmichel** [comment]
I think `attribute(forwarded=True)` looks neat and explicit. As long as we don't use `fw` I'm fine with it.

**Comment by NexeyaSGara** [comment]
I changed it for the next POGO release

**Comment by jairomoldes** [comment]
I think that "attribute(forwarded=True)" is the best option, but I don't have a strong opinion against the other option.

**Comment by jairomoldes** [comment]
Anyone working on this? I can have a look.

**Comment by NexeyaSGara** [comment]
Pascal Verdier produced a new Pogo version with the API like this :
attribute(forwarded=True)

**Comment by jairomoldes** [comment]
Could you please tell me where I can find it? I've been able to run both pogo 9.4.0 and 9.4.1 from a checkout of svn, but when it comes to generate pyhon code I get this error:
"Forwarded attributes are not supported in Python !"

If I select "PythonHL" then the code is generated, but there is no reference at all to "forwarded" attributes.

**Comment by jairomoldes** [comment]
I have been working on this but still pending on cppTango. See:

https://github.com/tango-controls/cppTango/pull/342
