### ISSUE TITLE
No-numpy builds

### ISSUE THREAD

**Issue by vxgmichel** [tango-controls/pytango#71]
Out of curiosity, what is the point in supporting no-numpy builds?

**Comment by tiagocoutinho** [comment]
It comes from a long time ago (in a galaxy far, far way) when numpy was not easily available on all platforms.
We considered that people might not want to have to build and install numpy on windows for example in some strange python versions.

Also numpy adds quite a few megabytes of private memory (~15Mb per process), so if you want to run scalable servers (or clients) in an embeded system (rasperry PI) this could be a lighter solution (assuming the server is not dumping 1D/2D attributes or commands, of course)

In practice, today, I would say it is an unused feature.

**Comment by vxgmichel** [comment]
Understood. I guess there is no reason to remove it for now, but it's something we can think about if it ever gets in our way. Thanks!
