### ISSUE TITLE
Release version 9.2.1

### ISSUE THREAD

**Issue by vxgmichel** [tango-controls/pytango#86]
After PR #85 is merged, I'd like to release pytango-9.2.1, and change the milestone for the pending issues to 9.2.2. Is it OK with everyone?

For the record, the release procedure includes:
- Editing the changelog
- Bumping the version
- Merging develop into master
- Make sure Travis is OK
- Make sure the documentation is updated
- Create a release tag on GitHub
- Upload the new version to PyPI
- Bumping the version with "-dev" in the develop branch
- Advertise the release on the mailing list

**Comment by jairomoldes** [comment]
Fine with me

**Comment by vxgmichel** [comment]
OK, I'll take care of it once PR #90 is merged and issue #89 is solved.
