### ISSUE TITLE
Case sensitivity error when subscribing to a change event.

### ISSUE THREAD

**Issue by gcerretani** [tango-controls/pytango#87]
When I subscribe to a change event, in the first event received at the subscription time the attr_value.name value has the right case sensitivity, as it was in PyTango 8. Then, the following change events have that field lower cased.

In the PERIODIC_EVENT, that field is always lower cased. It would be nice to get the not lowered name, as in PyTango 8.

Example:

- first event:
```
EventData[
     attr_name = 'tango://...:20000/satserver/lab/1/g2'
    attr_value = DeviceAttribute(data_format = tango._tango.AttrDataFormat.SCALAR, dim_x = 1, dim_y = 0, has_failed = False, is_empty = False, name = 'G2', nb_read = 1, nb_written = 1, quality = tango._tango.AttrQuality.ATTR_VALID, r_dimension = AttributeDimension(dim_x = 1, dim_y = 0), time = TimeVal(tv_nsec = 0, tv_sec = 1484308260, tv_usec = 881227), type = tango._tango.CmdArgType.DevDouble, value = 8.0, w_dim_x = 1, w_dim_y = 0, w_dimension = AttributeDimension(dim_x = 1, dim_y = 0), w_value = 0.0)
        device = SatServer(satserver/lab/1)
           err = False
        errors = ()
         event = 'change'
reception_date = TimeVal(tv_nsec = 0, tv_sec = 1484308261, tv_usec = 822368)]
```

- standard event:

```
EventData[
     attr_name = 'tango://...:20000/satserver/lab/1/g2'
    attr_value = DeviceAttribute(data_format = tango._tango.AttrDataFormat.SCALAR, dim_x = 1, dim_y = 0, has_failed = False, is_empty = False, name = 'g2', nb_read = 1, nb_written = 1, quality = tango._tango.AttrQuality.ATTR_VALID, r_dimension = AttributeDimension(dim_x = 1, dim_y = 0), time = TimeVal(tv_nsec = 0, tv_sec = 1484308266, tv_usec = 881001), type = tango._tango.CmdArgType.DevDouble, value = 7.96219999999992, w_dim_x = 1, w_dim_y = 0, w_dimension = AttributeDimension(dim_x = 1, dim_y = 0), w_value = 7.0)
        device = SatServer(satserver/lab/1)
           err = False
        errors = ()
         event = 'change'
reception_date = TimeVal(tv_nsec = 0, tv_sec = 1484308266, tv_usec = 929997)]
```

**Comment by gcerretani** [comment]
Hi Vincent. You've closed the bug report, but I do not understand if it has been solved or not. Should I report it in another repository?

**Comment by vxgmichel** [comment]
@gcerretani Sorry, I might have been too hasty discarding it as a pytango issue :sweat_smile:. I'll have a closer look. Can you confirm that this issue does not happen when using a pytango8 client with a tango9 server?

**Comment by gcerretani** [comment]
No, it does not. However, I've tried just right now that it happens also with a C++ TANGO 9 client.

Following the example in TANGO documentation ([here](http://www.esrf.eu/computing/cs/tango/tango_doc/kernel_doc/ds_prog/node5.html#SECTION00565250000000000000)), i get:

`
DoubleEventCallBack::push_event(): called attribute MAR_TX_SET event change (err=0)
DoubleEventCallBack::push_event(): called attribute mar_tx_set event change (err=0)
`

**Comment by vxgmichel** [comment]
Yes, I think you just proved that the lowering of the attribute name comes from the C++ layer on the client side. You might want to check if the issue still happens with tango 9.2.5 and report it on [tango-controls/cppTango](https://github.com/tango-controls/cppTango). Thanks again!
