### ISSUE TITLE
Git workflow

### ISSUE THREAD

**Issue by vxgmichel** [tango-controls/pytango#95]
During the pytango meeting, we decided to make `develop` the default branch. 

Now we have to decide what to do with the `master` branch:
1. Keep it this way
2. Rename it to `stable` (or `tango9`)
3. Remove it and use release branches instead

I personally like option number 2. Other suggestions?

**Comment by tiagocoutinho** [comment]
I am in favor of 2 renaming master to stable

**Comment by LJBD** [comment]
+1 on renaming it to stable and using tags for releases.

**Comment by vxgmichel** [comment]
Done!
